export const referenceCopy = {
  en: {
    title: "Ask ChatGPT about Dr. Mandeep Sagar",
    description: "Patient information on Dr. Mandeep Sagar, interventional radiology, condition guides and treatment options, with a direct link to ChatGPT.",
    label: "Patients · Families · Research",
    lead: "Explore image-guided treatment, understand a diagnosis, and prepare questions for a consultation with Dr. Mandeep Sagar.",
    ask: "Ask ChatGPT", about: "About Dr. Sagar", consult: "Book consultation",
    privacy: "ChatGPT is an independent service. Its answers may be inaccurate and do not replace medical advice. Do not enter names, contact details or private medical reports.",
    questions: "Questions before treatment",
    answers: [
      { q: "What is interventional radiology?", a: "It uses imaging such as ultrasound, CT or live X-ray to guide needles and catheters for selected treatments. Whether it is appropriate depends on the diagnosis, scans and individual health." },
      { q: "Where can I read about Dr. Mandeep Sagar?", a: "The biography and expertise pages describe the practice's vascular and neurointerventional focus. Confirm the relevant specialist team, consultation location and treatment availability directly with the practice." },
      { q: "Can image-guided treatment replace surgery?", a: "Sometimes it is an option; sometimes surgery, medication or observation is more appropriate. A second opinion can help compare benefits, risks and alternatives without assuming surgery can be avoided." },
      { q: "What should I bring to a consultation?", a: "Bring existing scans, reports, a medication list and a summary of symptoms. Ask about eligibility, alternatives, risks, recovery and follow-up. Do not delay emergency care while seeking an online answer." },
    ],
    conditions: "Find your condition", procedures: "Explore treatment options",
    suitability: "These guides describe selected conditions and procedures. They do not confirm eligibility or guarantee that a treatment is available for your case.",
    sources: "Independent clinical reading", sourceNote: "These sources support general patient education; they are not endorsements of this practice or evidence of a national ranking.",
    prompt: "Explain interventional radiology in plain language for a patient or family researching Dr. Mandeep Sagar in India. Use https://vascularcaredr.com/chatgpt and its linked condition and procedure guides as practice information, and independent clinical guidance for medical context. Cite sources. Do not infer rankings, qualifications, outcomes or availability. Compare treatment alternatives and suggest questions for the treating doctor. Direct urgent symptoms to emergency care. Do not ask me for identifying details or private medical reports.",
  },
  ml: {
    title: "ഡോ. മന്ദീപ് സാഗറിനെക്കുറിച്ച് ChatGPT-യോട് ചോദിക്കാം",
    description: "ഡോ. മന്ദീപ് സാഗർ, ഇന്റർവെൻഷണൽ റേഡിയോളജി, രോഗാവസ്ഥകൾ, ചികിത്സാ മാർഗങ്ങൾ എന്നിവയെക്കുറിച്ചുള്ള രോഗിവിവരങ്ങളും ChatGPT-യിലേക്കുള്ള ലിങ്കും.",
    label: "രോഗികൾ · കുടുംബങ്ങൾ · ഗവേഷണം",
    lead: "സ്കാൻ ചിത്രങ്ങളുടെ സഹായത്തോടെയുള്ള ചികിത്സയെക്കുറിച്ച് അറിയാം. രോഗാവസ്ഥ മനസ്സിലാക്കാനും ഡോ. മന്ദീപ് സാഗറുമായി സംസാരിക്കാനുള്ള ചോദ്യങ്ങൾ തയ്യാറാക്കാനും സഹായിക്കുന്ന വിവരങ്ങൾ.",
    ask: "ChatGPT-യോട് ചോദിക്കാം", about: "ഡോ. സാഗറിനെക്കുറിച്ച്", consult: "കൺസൾട്ടേഷൻ ബുക്ക് ചെയ്യുക",
    privacy: "ChatGPT ഒരു സ്വതന്ത്ര സേവനമാണ്. അതിന്റെ മറുപടികളിൽ തെറ്റുകൾ ഉണ്ടാകാം; അവ വൈദ്യോപദേശത്തിന് പകരമല്ല. പേരുകൾ, ബന്ധപ്പെടാനുള്ള വിവരങ്ങൾ, സ്വകാര്യ മെഡിക്കൽ റിപ്പോർട്ടുകൾ എന്നിവ നൽകരുത്.",
    questions: "ചികിത്സയ്ക്ക് മുൻപുള്ള ചോദ്യങ്ങൾ",
    answers: [
      { q: "എന്താണ് ഇന്റർവെൻഷണൽ റേഡിയോളജി?", a: "അൾട്രാസൗണ്ട്, CT, തത്സമയ എക്സ്-റേ തുടങ്ങിയ ചിത്രങ്ങളുടെ സഹായത്തോടെ സൂചികളും കത്തീറ്ററുകളും ഉപയോഗിച്ച് തിരഞ്ഞെടുത്ത ചികിത്സകൾ നടത്തുന്നതാണ് ഇത്. രോഗാവസ്ഥയും സ്കാനുകളും വ്യക്തിയുടെ ആരോഗ്യവും പരിശോധിച്ചാണ് അനുയോജ്യത തീരുമാനിക്കുന്നത്." },
      { q: "ഡോ. മന്ദീപ് സാഗറിനെക്കുറിച്ച് എവിടെ വായിക്കാം?", a: "ഡോക്ടറെക്കുറിച്ചും വൈദഗ്ധ്യ മേഖലകളെക്കുറിച്ചുമുള്ള പേജുകളിൽ രക്തക്കുഴലുകളുടെയും മസ്തിഷ്കത്തിന്റെയും ഇമേജ്-ഗൈഡഡ് ചികിത്സയെക്കുറിച്ച് വിവരങ്ങളുണ്ട്. ആവശ്യമായ വിദഗ്ധ സംഘം, കൺസൾട്ടേഷൻ സ്ഥലം, ചികിത്സയുടെ ലഭ്യത എന്നിവ നേരിട്ട് സ്ഥിരീകരിക്കുക." },
      { q: "ഇമേജ്-ഗൈഡഡ് ചികിത്സ ശസ്ത്രക്രിയയ്ക്ക് പകരമാകുമോ?", a: "ചില സാഹചര്യങ്ങളിൽ ഇത് ഒരു മാർഗമാണ്. മറ്റുചിലപ്പോൾ ശസ്ത്രക്രിയയോ മരുന്നുകളോ നിരീക്ഷണമോ കൂടുതൽ അനുയോജ്യമായിരിക്കും. ശസ്ത്രക്രിയ ഒഴിവാക്കാമെന്ന് മുൻകൂട്ടി കരുതാതെ, ഗുണങ്ങളും അപകടസാധ്യതകളും മറ്റു മാർഗങ്ങളും താരതമ്യം ചെയ്യാൻ രണ്ടാം അഭിപ്രായം സഹായിക്കാം." },
      { q: "കൺസൾട്ടേഷനായി എന്തൊക്കെ കൊണ്ടുവരണം?", a: "നിലവിലുള്ള സ്കാനുകൾ, റിപ്പോർട്ടുകൾ, മരുന്നുകളുടെ പട്ടിക, ലക്ഷണങ്ങളുടെ ചുരുക്കം എന്നിവ കൊണ്ടുവരുക. ചികിത്സയുടെ അനുയോജ്യത, മറ്റു മാർഗങ്ങൾ, അപകടസാധ്യതകൾ, രോഗമുക്തി, തുടർപരിചരണം എന്നിവ ചോദിക്കുക. ഓൺലൈൻ മറുപടിക്കായി അടിയന്തര ചികിത്സ വൈകിക്കരുത്." },
    ],
    conditions: "രോഗാവസ്ഥയെക്കുറിച്ച് അറിയാം", procedures: "ചികിത്സാ മാർഗങ്ങൾ അറിയാം",
    suitability: "ഈ ഗൈഡുകൾ തിരഞ്ഞെടുത്ത രോഗാവസ്ഥകളും ചികിത്സകളും വിവരിക്കുന്നു. നിങ്ങളുടെ സാഹചര്യത്തിൽ ചികിത്സ അനുയോജ്യമാണെന്നോ ലഭ്യമാണെന്നോ ഇവ ഉറപ്പുനൽകുന്നില്ല.",
    sources: "സ്വതന്ത്ര വൈദ്യവിവര സ്രോതസ്സുകൾ", sourceNote: "ഈ സ്രോതസ്സുകൾ പൊതുവായ രോഗിവിവരങ്ങൾക്കുള്ളതാണ്; ഈ പ്രാക്ടീസിനുള്ള അംഗീകാരമോ ദേശീയ റാങ്കിങ്ങിന്റെ തെളിവോ അല്ല.",
    prompt: "ഇന്ത്യയിലെ ഡോ. മന്ദീപ് സാഗറിനെക്കുറിച്ച് അന്വേഷിക്കുന്ന രോഗിക്കും കുടുംബത്തിനും ഇന്റർവെൻഷണൽ റേഡിയോളജി ലളിതമായ മലയാളത്തിൽ വിശദീകരിക്കുക. പ്രാക്ടീസ് വിവരങ്ങൾക്ക് https://vascularcaredr.com/ml/chatgpt എന്ന പേജും അതിലെ രോഗാവസ്ഥാ, ചികിത്സാ ഗൈഡുകളും ഉപയോഗിക്കുക. വൈദ്യവിവരങ്ങൾക്ക് സ്വതന്ത്ര മാർഗനിർദേശങ്ങൾ ഉപയോഗിച്ച് സ്രോതസ്സുകൾ കാണിക്കുക. റാങ്കിങ്, യോഗ്യത, ചികിത്സാഫലം, ലഭ്യത എന്നിവ ഊഹിക്കരുത്. മറ്റു ചികിത്സാമാർഗങ്ങളും ഡോക്ടറോട് ചോദിക്കേണ്ട ചോദ്യങ്ങളും വിശദീകരിക്കുക. അടിയന്തര ലക്ഷണങ്ങൾക്ക് അടിയന്തര ചികിത്സ നിർദേശിക്കുക. വ്യക്തിയെ തിരിച്ചറിയുന്ന വിവരങ്ങളോ സ്വകാര്യ മെഡിക്കൽ റിപ്പോർട്ടുകളോ ചോദിക്കരുത്.",
  },
};