import type { Pillar } from "./types";

export const brainAvm: Pillar = {
  slug: "brain-avm-avf",
  name: "Brain AVM / AVF",
  title: "Brain AVM and AVF",
  heroQuote: "A tangle of vessels was found on my scan.",
  heroLead:
    "An arteriovenous malformation is a short circuit — arteries emptying directly into veins with no capillary bed in between. The veins take arterial pressure they were never built for. Embolization closes the short circuit from inside the vessel, one feeder at a time.",
  summary:
    "Abnormal direct connections between brain arteries and veins. Embolization closes the shunt through a microcatheter, alone or before surgery or radiosurgery.",

  symptoms: [
    "Seizure, often the first presentation in an unruptured AVM",
    "Sudden severe headache with vomiting if bleeding occurs",
    "Weakness, numbness or speech difficulty from a bleed or from steal of blood flow",
    "Pulsatile whooshing sound heard in the ear, typical of a dural fistula",
    "Progressive headaches",
    "Visual disturbance",
    "Red, congested eye with bulging, in a carotid cavernous fistula",
    "Cognitive slowing or personality change in high-flow lesions",
  ],
  causes: [
    "Congenital abnormality of vessel development, present from birth (AVM)",
    "Acquired abnormal connection following venous sinus thrombosis (dural AVF)",
    "Head trauma creating a direct arterial-venous connection",
    "Rupture of an internal carotid aneurysm into the cavernous sinus (carotid cavernous fistula)",
    "Previous craniotomy or infection, rarely",
    "Hereditary haemorrhagic telangiectasia, in which multiple malformations occur",
  ],
  riskFactors: [
    "Family history of vascular malformation",
    "Hereditary haemorrhagic telangiectasia",
    "Previous head injury for fistulas",
    "Previous cerebral venous sinus thrombosis",
    "Previous bleed from the same lesion, which raises the risk of another",
    "High blood pressure, which increases bleeding risk once a lesion exists",
  ],
  warningSigns: [
    "Sudden severe headache with vomiting or reduced consciousness — emergency",
    "First-ever seizure in an adult",
    "New pulsatile noise in the ear, especially with visual change",
    "A red, protruding eye with double vision",
    "Any new weakness, speech difficulty or visual loss",
  ],
  diagnosis: [
    { step: "History", detail: "Seizures, headache pattern, pulsatile tinnitus, previous trauma or clot, and any family history of vascular malformations." },
    { step: "Clinical examination", detail: "Full neurological examination, eye assessment for proptosis and congestion, and auscultation over the skull and orbit for a bruit." },
    { step: "Blood tests", detail: "Baseline count, clotting and kidney function before contrast studies and intervention." },
    { step: "Imaging", detail: "CT and CT angiography acutely, MRI for the relationship to functional brain, and catheter angiography to define feeders, nidus and draining veins." },
  ],
  tests: [
    { name: "CT and CT angiography", why: "The acute study — it shows bleeding immediately and gives a first map of the abnormal vessels." },
    { name: "MRI with MR angiography", why: "Shows where the malformation sits relative to speech, motor and visual areas, and detects old microbleeds that indicate previous silent haemorrhage." },
    { name: "Digital subtraction angiography", why: "The definitive study. Only this shows the feeding arteries, the nidus architecture and the direction and pattern of venous drainage in real time — the basis of the entire treatment plan." },
    { name: "Superselective angiography", why: "Performed with a microcatheter inside individual feeders during treatment, confirming the target before any embolic material is injected." },
    { name: "Functional MRI or tractography", why: "Maps eloquent brain and white matter tracts when the lesion lies close to critical areas." },
    { name: "EEG", why: "Used when seizures are the presentation, to characterise them and guide medication." },
  ],
  treatments: [
    { name: "Endovascular embolization", kind: "Endovascular", detail: "Liquid embolic agent or coils are delivered through a microcatheter to close feeding arteries and the nidus, from inside the vessel." },
    { name: "Staged embolization", kind: "Endovascular", detail: "Large malformations are treated over several sessions, allowing the brain to adapt to flow changes between stages." },
    { name: "Stereotactic radiosurgery", kind: "Observation", detail: "Focused radiation causes gradual obliteration of small malformations over two to three years, often after embolization has reduced the size." },
    { name: "Microsurgical resection", kind: "Surgery", detail: "Surgical removal, frequently after embolization has reduced flow and bleeding risk during the operation." },
    { name: "Transvenous embolization", kind: "Endovascular", detail: "The route of choice for many dural fistulas and carotid cavernous fistulas, approaching the abnormal connection through the draining vein." },
    { name: "Antiepileptic medication", kind: "Medication", detail: "Controls seizures. It treats the symptom, not the malformation." },
    { name: "Observation", kind: "Observation", detail: "Considered for some unruptured, low-risk malformations, where treatment risk may exceed the natural risk of the lesion." },
  ],
  approach: [
    "Nothing is decided without a full diagnostic angiogram. Cross-sectional imaging alone cannot show the architecture that determines risk.",
    "Angioarchitecture is graded — nidus size, venous drainage pattern, associated aneurysms and eloquence of the surrounding brain.",
    "Treatment intent is stated openly at the start: curative embolization, preparation for surgery, preparation for radiosurgery, or targeted treatment of a high-risk feature.",
    "Superselective injection precedes every embolization, to confirm the microcatheter is not supplying normal brain.",
    "Large lesions are staged deliberately, because closing high flow too quickly can cause dangerous breakthrough bleeding.",
    "Dural fistulas with cortical venous reflux are treated actively, as this feature carries a high annual bleeding risk.",
  ],
  procedures: ["embolization", "aneurysm-coiling"],
  recovery: [
    { when: "Day 0", what: "Recovery in a monitored or intensive care setting after general anaesthesia, with strict blood pressure control." },
    { when: "Day 1 to 2", what: "Neurological observation and imaging where required. Many patients are mobile the next day." },
    { when: "Days 3 to 7", what: "Discharge for uncomplicated cases, with a clear plan for the next stage of treatment if the course is staged." },
    { when: "Weeks 2 to 8", what: "Return to normal activity for unruptured cases; rehabilitation continues where there has been a bleed." },
    { when: "Month 3 to 6", what: "Follow-up angiography to assess residual filling and plan the next session, surgery or radiosurgery." },
    { when: "Year 1 to 3", what: "Long-term surveillance, particularly after radiosurgery, which takes years to complete obliteration." },
  ],
  prevention: [
    "AVMs are congenital and cannot be prevented; the aim is preventing a bleed",
    "Keep blood pressure well controlled",
    "Avoid stimulant drugs",
    "Take antiepileptic medication exactly as prescribed if seizures have occurred",
    "Attend every scheduled surveillance scan after partial treatment or radiosurgery",
    "Report new headache, seizure, weakness or visual change without delay",
    "Discuss pregnancy planning in advance if a malformation is untreated",
  ],
  faqs: [
    { q: "What is a brain AVM?", a: "A tangle of abnormal vessels where arteries connect directly to veins without capillaries in between, exposing thin-walled veins to arterial pressure." },
    { q: "What is the difference between an AVM and an AVF?", a: "An AVM has a nidus — a tangle between artery and vein. A fistula is a direct connection with no nidus, and is usually acquired rather than congenital." },
    { q: "What is a carotid cavernous fistula?", a: "An abnormal connection between the carotid artery and the venous sinus behind the eye, causing a red, bulging, pulsating eye and double vision. It is treatable endovascularly." },
    { q: "Will my AVM bleed?", a: "The average annual risk is low but not zero, and rises with previous haemorrhage, deep venous drainage and associated aneurysms. Angiography defines your individual risk." },
    { q: "What is embolization?", a: "Delivery of a liquid embolic agent or coils through a microcatheter to seal the abnormal connection from inside the vessel." },
    { q: "Can embolization cure an AVM completely?", a: "Small malformations with few feeders can be cured endovascularly. Larger ones usually require embolization combined with surgery or radiosurgery." },
    { q: "Why is treatment done in stages?", a: "Closing a high-flow malformation too abruptly can overload surrounding brain vessels and cause bleeding. Staging allows the circulation to adjust." },
    { q: "Is the procedure done awake?", a: "No. It is performed under general anaesthesia, since absolute stillness is required for precise navigation." },
    { q: "How long does it take?", a: "Two to four hours per session, depending on the number of feeders treated." },
    { q: "What are the risks?", a: "Bleeding, stroke from occlusion of a normal branch, glue or embolic material migration and access site complications. These are set against the lifetime risk of leaving the lesion untreated." },
    { q: "What is radiosurgery?", a: "Focused radiation that causes the malformation to close gradually over two to three years. It suits small lesions and deep locations." },
    { q: "Should every AVM be treated?", a: "No. For some unruptured malformations, the risk of treatment can exceed the natural risk. This is discussed openly with the angiogram in front of you." },
    { q: "Can I have children with an untreated AVM?", a: "Many women do, but pregnancy and delivery need to be planned with neurology and obstetrics involved." },
    { q: "Why do I hear a whooshing sound?", a: "Turbulent high-flow blood passing through the abnormal connection, transmitted to the ear. It is characteristic of a dural fistula." },
    { q: "Are AVMs inherited?", a: "Most are sporadic. A minority occur in hereditary haemorrhagic telangiectasia, which does run in families." },
    { q: "Can an AVM cause epilepsy?", a: "Yes, seizures are a common presentation of unruptured AVMs and are managed with medication alongside treatment planning." },
    { q: "Will I need lifelong monitoring?", a: "Yes, particularly after partial treatment or radiosurgery, until imaging confirms complete obliteration." },
    { q: "Can an AVM come back after complete treatment?", a: "Recurrence is uncommon in adults after documented complete obliteration, but more possible in children, so follow-up continues." },
    { q: "Does exercise increase the risk?", a: "Extreme straining is generally discouraged in untreated lesions. Individual advice depends on the angiographic features." },
    { q: "What is cortical venous reflux and why does it matter?", a: "Abnormal drainage backward into surface brain veins. It markedly increases bleeding risk and usually prompts active treatment." },
  ],
  relatedConditions: ["brain-avm", "dural-avf", "cerebral-aneurysm", "carotid-cavernous-fistula"],
  relatedSymptoms: ["Seizure", "Pulsatile noise in the ear", "Sudden headache", "Red bulging eye", "Weakness or speech difficulty"],
};
