import type { Pillar } from "./types";

export const brainAneurysm: Pillar = {
  slug: "brain-aneurysm",
  name: "Brain Aneurysm",
  title: "Brain aneurysm",
  heroQuote: "The worst headache of my life.",
  heroLead:
    "An aneurysm is a weak spot on a brain artery that balloons outward. Most are silent. The ones that tear announce themselves with a headache unlike any other. Both can be treated from inside the vessel, filling the sac with fine coils until blood no longer enters it.",
  summary:
    "A ballooned weak point on a brain artery. Endovascular coiling or flow diversion seals it from inside the vessel, without opening the skull.",

  symptoms: [
    "Sudden, explosive headache reaching maximum intensity within seconds — the hallmark of rupture",
    "Neck stiffness and intolerance of light",
    "Vomiting with the headache",
    "Brief loss of consciousness or collapse",
    "Double vision or a drooping eyelid, from pressure on the nerve to the eye",
    "A dilated pupil on one side",
    "Seizure",
    "Most unruptured aneurysms cause no symptoms at all and are found incidentally",
  ],
  causes: [
    "Weakness in the arterial wall at branch points, where flow stress is highest",
    "Long-standing high blood pressure",
    "Smoking, which both weakens the wall and increases rupture risk",
    "Inherited connective tissue disorders such as Ehlers-Danlos or Marfan syndrome",
    "Autosomal dominant polycystic kidney disease",
    "Arterial dissection or trauma",
    "Infection of the vessel wall, producing a mycotic aneurysm",
  ],
  riskFactors: [
    "Smoking",
    "High blood pressure",
    "Family history of aneurysm or subarachnoid haemorrhage",
    "Polycystic kidney disease",
    "Female sex, particularly after menopause",
    "Age above 40",
    "Heavy alcohol use",
    "Cocaine or stimulant use",
  ],
  warningSigns: [
    "A sudden severe headache unlike any previous headache — call emergency services immediately",
    "Headache with neck stiffness, vomiting or light intolerance",
    "A new drooping eyelid or double vision, which can precede rupture",
    "A brief severe headache days earlier — a sentinel bleed that must not be dismissed",
    "Any collapse or seizure with headache",
  ],
  diagnosis: [
    { step: "History", detail: "The speed of headache onset is the critical detail. Thunderclap onset means subarachnoid haemorrhage until proven otherwise." },
    { step: "Clinical examination", detail: "Conscious level, pupil size and reaction, eye movements, neck stiffness and focal neurological deficit are documented and graded." },
    { step: "Blood tests", detail: "Full blood count, clotting, electrolytes and kidney function, both for baseline and to prepare for contrast and intervention." },
    { step: "Imaging", detail: "Urgent CT of the head, then CT angiography. Lumbar puncture if CT is negative but suspicion remains, and catheter angiography for definitive anatomy." },
  ],
  tests: [
    { name: "Non-contrast CT head", why: "Detects blood in the subarachnoid space with very high sensitivity in the first hours. It is the immediate test in any thunderclap headache." },
    { name: "CT angiography", why: "Locates the aneurysm, measures its neck and dome, and shows the surrounding branches — the information that decides coiling versus clipping." },
    { name: "Lumbar puncture", why: "Performed when CT is negative but the history is convincing. Blood breakdown pigment in the fluid confirms a bleed that CT has missed." },
    { name: "Digital subtraction angiography", why: "The reference standard, with 3D rotational imaging. It shows small aneurysms other studies miss and defines the working projection for treatment." },
    { name: "MR angiography", why: "Used for screening and for follow-up surveillance without radiation or iodinated contrast." },
    { name: "Transcranial Doppler", why: "Monitors for vasospasm in the days after a bleed, when arteries can narrow and cause a delayed stroke." },
  ],
  treatments: [
    { name: "Endovascular coiling", kind: "Endovascular", detail: "Fine platinum coils are packed into the aneurysm sac through a microcatheter until blood no longer enters it and the sac clots off." },
    { name: "Balloon or stent-assisted coiling", kind: "Endovascular", detail: "Used for wide-necked aneurysms, where a balloon or stent holds the coils inside the sac and protects the parent artery." },
    { name: "Flow diversion", kind: "Endovascular", detail: "A dense mesh stent placed across the neck redirects flow past the aneurysm, which thromboses and shrinks over months. Used for large or complex aneurysms." },
    { name: "Surgical clipping", kind: "Surgery", detail: "A titanium clip placed across the neck through a craniotomy. Preferred for some anatomy, particularly wide-necked middle cerebral aneurysms." },
    { name: "Blood pressure control", kind: "Medication", detail: "Fundamental both to prevent rupture and to manage the acute phase after a bleed." },
    { name: "Nimodipine", kind: "Medication", detail: "Given after subarachnoid haemorrhage to reduce the risk of delayed ischemic injury from vasospasm." },
    { name: "Surveillance", kind: "Observation", detail: "Small, low-risk unruptured aneurysms may be monitored with interval imaging rather than treated." },
  ],
  approach: [
    "A ruptured aneurysm is secured as early as possible — the highest risk of a second bleed is within the first days.",
    "Anatomy decides technique. Neck width, dome-to-neck ratio, branch involvement and vessel tortuosity are assessed on 3D angiography before a device is chosen.",
    "Access is through the wrist or groin. The skull is not opened, and there is no brain retraction.",
    "Wide-necked and complex aneurysms are treated with balloon assistance, stent assistance or flow diversion rather than forced into simple coiling.",
    "Unruptured aneurysms are discussed honestly: size, location, growth and patient age are weighed against the risk of treatment, and observation is a legitimate outcome of that discussion.",
    "Follow-up imaging is scheduled from the outset, because coil compaction and recurrence must be detected early.",
  ],
  procedures: ["aneurysm-coiling", "embolization"],
  recovery: [
    { when: "Day 0", what: "After coiling, care continues in intensive care for ruptured cases, with blood pressure control and monitoring of conscious level." },
    { when: "Days 1 to 3", what: "Unruptured patients are usually discharged within a day or two. Ruptured patients remain monitored for vasospasm." },
    { when: "Days 4 to 14", what: "The vasospasm window after a bleed, monitored with Doppler and treated promptly if it develops." },
    { when: "Weeks 2 to 6", what: "Gradual return to activity for unruptured cases. After a bleed, fatigue and headache commonly persist for weeks." },
    { when: "Month 3 to 6", what: "First follow-up angiography or MR angiography to confirm the aneurysm remains occluded." },
    { when: "Year 1 and beyond", what: "Ongoing surveillance imaging at intervals, with lifelong blood pressure control and no smoking." },
  ],
  prevention: [
    "Stop smoking completely — the single strongest modifiable factor",
    "Keep blood pressure consistently controlled",
    "Avoid stimulant drugs",
    "Limit alcohol",
    "Consider screening if two or more first-degree relatives have had an aneurysm",
    "Screening is advised in polycystic kidney disease",
    "Attend scheduled surveillance scans for known untreated aneurysms",
  ],
  faqs: [
    { q: "What is a brain aneurysm?", a: "A weakened, ballooned area on the wall of a brain artery. It may remain stable for life or, less commonly, tear and bleed." },
    { q: "Will my aneurysm burst?", a: "Most do not. Risk depends on size, location, shape, growth on serial imaging, smoking, blood pressure and family history." },
    { q: "What does a rupture feel like?", a: "A sudden, explosive headache reaching maximum severity within seconds, often with vomiting, neck stiffness and light intolerance." },
    { q: "What is coiling?", a: "Soft platinum coils are delivered through a microcatheter into the aneurysm until it is packed and blood can no longer enter. The skull is not opened." },
    { q: "Coiling or clipping — which is better?", a: "Neither is universally better. Coiling avoids open surgery and generally has a faster recovery; clipping suits certain anatomy. The decision is made on the angiogram." },
    { q: "What is a flow diverter?", a: "A fine-mesh stent placed in the parent artery across the aneurysm neck. It redirects flow so the aneurysm clots and shrinks over months." },
    { q: "How long does coiling take?", a: "Typically one to three hours depending on the complexity of the anatomy." },
    { q: "Is coiling done under general anaesthesia?", a: "Yes, usually, so the patient is completely still during precise work inside small vessels." },
    { q: "What are the risks?", a: "Rupture during the procedure, clot formation causing stroke, coil migration and access site complications. These are weighed against the risk of leaving the aneurysm untreated." },
    { q: "Will I need lifelong follow-up?", a: "Yes, with interval imaging. Coils can compact and aneurysms occasionally recur, and new aneurysms can form." },
    { q: "Can an aneurysm come back after coiling?", a: "A minority recur, particularly larger and wide-necked ones. That is why surveillance imaging is scheduled." },
    { q: "Do I need blood thinners after treatment?", a: "After stent-assisted coiling or flow diversion, dual antiplatelet therapy is required for a period. Simple coiling usually does not need it." },
    { q: "Should my family be screened?", a: "Screening is generally offered when two or more first-degree relatives have had an aneurysm, or with polycystic kidney disease." },
    { q: "Can I exercise with an untreated aneurysm?", a: "Moderate exercise is generally acceptable; heavy straining and extreme exertion are usually discouraged. Advice is individual." },
    { q: "Does stress cause rupture?", a: "Rupture often occurs during ordinary activity. Sustained high blood pressure matters far more than momentary stress." },
    { q: "What is a sentinel headache?", a: "A brief severe headache days or weeks before a major bleed, caused by a small leak. It is an urgent warning and frequently missed." },
    { q: "What is vasospasm?", a: "Narrowing of brain arteries several days after a bleed, which can cause a delayed stroke. It is monitored for and treated actively." },
    { q: "Can I fly after coiling?", a: "Usually yes, once recovered and cleared at follow-up. Timing depends on whether there was a bleed." },
    { q: "Will an MRI be safe with coils in place?", a: "Modern coils and stents are MRI-compatible at standard field strengths. Always inform the radiographer." },
    { q: "Can small aneurysms just be watched?", a: "Yes. Many small, stable aneurysms in low-risk locations are monitored with imaging rather than treated." },
  ],
  relatedConditions: ["cerebral-aneurysm", "brain-avm", "dural-avf", "acute-ischemic-stroke"],
  relatedSymptoms: ["Sudden severe headache", "Neck stiffness", "Double vision", "Drooping eyelid", "Collapse with headache"],
};
