import type { Pillar } from "./types";

export const dvt: Pillar = {
  slug: "deep-vein-thrombosis",
  name: "Deep Vein Thrombosis",
  title: "Deep vein thrombosis",
  heroQuote: "One leg swelled up overnight.",
  heroLead:
    "A clot in the deep veins of the leg blocks the route blood takes back to the heart. The immediate danger is that part of it travels to the lungs. The long-term danger is a leg left permanently swollen and heavy — which early clot removal can prevent.",
  summary:
    "Sudden swelling and pain in one leg from a deep vein clot. Anticoagulation prevents extension; catheter-directed clot removal protects the valves in selected patients.",

  symptoms: [
    "Swelling of one leg, developing over hours to days",
    "Pain or tightness in the calf or thigh",
    "Warmth and redness over the swollen area",
    "Prominent surface veins on the affected leg",
    "Aching that worsens on standing and walking",
    "In extensive clot, a bluish, tensely swollen limb",
    "Breathlessness or chest pain — suggesting the clot has reached the lungs",
  ],
  causes: [
    "Immobility — long travel, bed rest, plaster casts, hospital admission",
    "Recent surgery, especially orthopaedic or pelvic",
    "Cancer and its treatments",
    "Pregnancy and the weeks after delivery",
    "Oestrogen-containing contraceptives or hormone therapy",
    "Inherited clotting disorders",
    "Compression of the left iliac vein by the crossing artery (May-Thurner syndrome)",
    "Central venous catheters and pacemaker leads for arm clots",
  ],
  riskFactors: [
    "Previous DVT or pulmonary embolism",
    "Family history of clotting",
    "Age above 60",
    "Obesity",
    "Smoking",
    "Active malignancy",
    "Prolonged immobility",
    "Dehydration",
    "Recent trauma or fracture",
  ],
  warningSigns: [
    "Sudden breathlessness, chest pain on breathing, coughing blood or fainting — call emergency services, this may be a pulmonary embolism",
    "A tensely swollen, blue and painful leg — extensive clot threatening the limb",
    "Rapidly increasing swelling despite starting treatment",
    "Do not massage a swollen calf",
  ],
  diagnosis: [
    { step: "History", detail: "Speed of onset, travel, surgery, immobility, hormone use, cancer, previous clots and family history." },
    { step: "Clinical examination", detail: "Circumference measured and compared with the other leg, tenderness along the deep veins, warmth, and assessment for breathlessness." },
    { step: "Blood tests", detail: "D-dimer to exclude clot in low-risk patients, plus full blood count, kidney function and clotting profile before anticoagulation." },
    { step: "Imaging", detail: "Compression duplex ultrasound confirms the clot and its extent; CT venography assesses the pelvic veins and CT pulmonary angiography the lungs." },
  ],
  tests: [
    { name: "Compression duplex ultrasound", why: "The main test. A vein that does not compress under the probe contains clot. It also shows how far up the clot extends, which changes management." },
    { name: "D-dimer", why: "Highly sensitive but not specific. A normal result in a low-risk patient safely excludes DVT; a raised one only means imaging is needed." },
    { name: "CT venography", why: "Looks above the groin, where ultrasound is unreliable, and identifies iliac vein compression as an underlying cause." },
    { name: "CT pulmonary angiography", why: "Performed when there is breathlessness or chest pain, to confirm or exclude pulmonary embolism." },
    { name: "Thrombophilia screen", why: "Considered in young patients, recurrent clots or a strong family history — the result may determine how long anticoagulation continues." },
    { name: "Cancer screening", why: "An unprovoked clot in an older patient warrants age-appropriate cancer assessment, as it can be the first sign." },
  ],
  treatments: [
    { name: "Anticoagulation", kind: "Medication", detail: "The foundation of treatment. It prevents the clot extending and embolising while the body dissolves it, but it does not itself remove clot." },
    { name: "Catheter-directed thrombolysis", kind: "Endovascular", detail: "Clot-dissolving drug delivered directly into the clot through a catheter over hours, used in extensive iliofemoral clot to preserve valves." },
    { name: "Pharmacomechanical thrombectomy", kind: "Endovascular", detail: "Combined drug and mechanical clot removal in a single session, reducing drug dose and treatment time." },
    { name: "Venous stenting", kind: "Endovascular", detail: "Used when an underlying iliac vein compression is found, to keep the vein open and prevent recurrence." },
    { name: "IVC filter", kind: "Endovascular", detail: "A temporary filter in the vena cava for patients who cannot receive anticoagulation, retrieved as soon as it is safe." },
    { name: "Graduated compression", kind: "Lifestyle", detail: "Reduces swelling and symptoms during recovery and helps limit post-thrombotic change." },
    { name: "Early mobilisation", kind: "Lifestyle", detail: "Walking is encouraged once anticoagulation is started — bed rest does not reduce embolism risk." },
  ],
  approach: [
    "The first decision is anatomical: clot confined below the knee behaves very differently from clot filling the iliac vein.",
    "Extensive iliofemoral clot in a younger, active patient is considered for catheter-directed removal, because anticoagulation alone often leaves a damaged, swollen leg.",
    "Any patient with left-sided iliofemoral DVT is assessed for iliac vein compression, which is otherwise missed and causes recurrence.",
    "Filters are used sparingly, always with a retrieval plan and date.",
    "The cause is pursued in every unprovoked case — duration of anticoagulation depends on it.",
    "Follow-up includes surveillance for post-thrombotic syndrome, which is preventable and often ignored.",
  ],
  procedures: ["thrombectomy"],
  recovery: [
    { when: "Day 0", what: "Anticoagulation begins immediately once diagnosis is confirmed. Walking is encouraged, not restricted." },
    { when: "Days 1 to 3", what: "Where intervention is indicated, catheter-directed lysis is performed and the vein reassessed daily." },
    { when: "Week 1 to 2", what: "Swelling begins to settle. Compression stocking worn during the day." },
    { when: "Month 1", what: "Review of symptoms, bleeding risk and adherence. Duplex to document the residual clot burden." },
    { when: "Months 3 to 6", what: "Decision on whether anticoagulation continues, based on whether the clot was provoked and on test results." },
    { when: "Year 1 and beyond", what: "Monitoring for post-thrombotic syndrome — persistent swelling, heaviness or skin change — which is treatable if identified." },
  ],
  prevention: [
    "Walk and flex the ankles hourly during long flights or drives",
    "Stay well hydrated when travelling",
    "Use prescribed prophylaxis after surgery or during hospital admission",
    "Wear compression stockings if you have had a previous clot",
    "Discuss clot risk before starting oestrogen-containing contraception",
    "Maintain a healthy weight and stop smoking",
    "Report one-sided leg swelling promptly rather than waiting to see if it settles",
  ],
  faqs: [
    { q: "What is deep vein thrombosis?", a: "A blood clot forming in the deep veins, usually of the leg, obstructing the return of blood to the heart." },
    { q: "How do I know if leg swelling is a clot?", a: "Clot typically affects one leg, develops over hours to days, and is accompanied by calf tightness or pain. Only an ultrasound can confirm it." },
    { q: "Is DVT dangerous?", a: "Yes. Part of the clot can travel to the lungs and cause a pulmonary embolism, which can be fatal. It is treatable when caught early." },
    { q: "What is a pulmonary embolism?", a: "A clot that has travelled to the lung arteries, causing sudden breathlessness, chest pain on breathing or collapse. It requires emergency care." },
    { q: "How is DVT diagnosed?", a: "Compression duplex ultrasound is the standard test. D-dimer helps exclude it in low-risk patients." },
    { q: "Can I walk with a DVT?", a: "Yes, once anticoagulation has started. Walking helps and does not increase the risk of embolism." },
    { q: "Should I massage the leg?", a: "No. Avoid massage over an acute clot." },
    { q: "How long will I be on blood thinners?", a: "At least three months. Longer or indefinitely if the clot was unprovoked, recurrent, or associated with cancer or a clotting disorder." },
    { q: "Do blood thinners dissolve the clot?", a: "They prevent it growing and travelling while the body's own system breaks it down. They do not directly dissolve it." },
    { q: "What is catheter-directed thrombolysis?", a: "A catheter is placed into the clot and a clot-dissolving drug infused directly, removing clot far faster and helping preserve the vein valves." },
    { q: "Who benefits from clot removal rather than tablets alone?", a: "Typically younger, active patients with extensive clot in the thigh and pelvic veins, treated within about two weeks of onset." },
    { q: "What is post-thrombotic syndrome?", a: "Chronic swelling, heaviness, discoloration and sometimes ulceration after a DVT, caused by damaged valves and residual obstruction." },
    { q: "Can DVT come back?", a: "Yes, particularly after unprovoked clots. Recurrence risk guides how long anticoagulation continues." },
    { q: "What is May-Thurner syndrome?", a: "Compression of the left iliac vein by the overlying right iliac artery, predisposing to left leg DVT. It is treated by stenting the vein." },
    { q: "Is flying safe after a DVT?", a: "Usually, once established on anticoagulation, with compression stockings, hydration and regular movement. Check with your physician first." },
    { q: "Does DVT happen in the arm?", a: "Yes, most often around central lines and pacemaker leads, or in athletes with thoracic outlet compression." },
    { q: "Should my family be tested?", a: "Testing is considered when there is a strong family history or clots at a young age. It is not routine for everyone." },
    { q: "Can I take contraceptive pills after a DVT?", a: "Oestrogen-containing pills are generally avoided afterwards. Alternative methods are discussed with your gynaecologist." },
    { q: "What is an IVC filter?", a: "A small device placed in the main abdominal vein to catch clots, used when blood thinners cannot be given. It should be removed once it is no longer needed." },
    { q: "Will my leg return to normal size?", a: "Most legs improve substantially over weeks to months. Compression and, in selected cases, early clot removal improve the final result." },
  ],
  relatedConditions: ["varicose-veins", "venous-ulcer", "central-vein-stenosis"],
  relatedSymptoms: ["Swelling in one leg", "Calf pain", "Warm red leg", "Breathlessness", "Heaviness after a clot"],
};
