import type { Pillar } from "./types";

export const diabeticFoot: Pillar = {
  slug: "diabetic-foot",
  name: "Diabetic Foot",
  title: "Diabetic foot",
  heroQuote: "My wound isn't healing.",
  heroLead:
    "A wound on a diabetic foot is rarely only a wound. It is usually a circulation problem wearing the disguise of an infection. Restore the blood supply and tissue that was declared unsalvageable often heals.",
  summary:
    "Non-healing foot ulcers in diabetes are usually a blood supply problem. Angioplasty below the knee restores flow and allows the wound to heal, avoiding amputation.",

  symptoms: [
    "A wound or ulcer that has not healed in weeks",
    "Blackened skin at a toe tip or heel",
    "Discharge, odour or surrounding redness",
    "Numbness or a burning, tingling sensation in the feet",
    "Cold feet, or one foot colder than the other",
    "Pain in the foot at night, relieved by hanging the leg down",
    "Thin, shiny skin and loss of hair on the lower leg",
    "Slow-growing, thickened toenails",
    "A callus that has broken down at its centre",
  ],
  causes: [
    "Peripheral arterial disease — narrowed or blocked arteries below the knee reduce oxygen delivery to the tissue",
    "Diabetic neuropathy — loss of sensation, so injury goes unnoticed until it is deep",
    "Abnormal pressure loading from foot deformity, causing callus and then breakdown",
    "Infection entering through a small break in the skin",
    "Poor glycaemic control, which impairs both healing and immune response",
    "Ill-fitting footwear and walking barefoot",
  ],
  riskFactors: [
    "Diabetes for more than ten years",
    "Poor blood sugar control",
    "Smoking",
    "Kidney disease or dialysis",
    "Previous ulcer or previous amputation",
    "Loss of protective sensation on testing",
    "Foot deformity — claw toes, Charcot foot, bunions",
    "Peripheral arterial disease",
    "Impaired vision, preventing daily self-examination",
  ],
  warningSigns: [
    "Any wound present for more than two weeks needs vascular assessment, not another dressing",
    "Blackening of a toe or heel — seek help the same day",
    "Fever, spreading redness or foul discharge suggests infection tracking deeper",
    "Sudden severe foot pain with pallor and coldness is an emergency",
    "An amputation recommended without a vascular study deserves a second opinion first",
  ],
  diagnosis: [
    { step: "History", detail: "How long the wound has been present, how it began, previous ulcers, smoking, dialysis, and whether there is rest pain at night." },
    { step: "Clinical examination", detail: "Pulses at the groin, knee, ankle and foot; wound depth probed to bone; sensation tested with a monofilament; the opposite foot always examined too." },
    { step: "Blood tests", detail: "HbA1c, inflammatory markers, kidney function and culture from the wound base rather than a surface swab." },
    { step: "Imaging", detail: "Doppler first, then CT or catheter angiography of the leg down to the pedal arch, because below-knee disease is where the answer usually lies." },
  ],
  tests: [
    { name: "Arterial Doppler ultrasound", why: "A painless first look at flow in the leg arteries. It shows where waveforms flatten out, pointing to the level of blockage." },
    { name: "Ankle-brachial and toe pressures", why: "Numbers that predict healing. In diabetes ankle vessels are often calcified and falsely high, so toe pressure is the more honest measure." },
    { name: "CT angiography", why: "Maps the whole arterial tree in one scan and plans the route a catheter will take before any puncture is made." },
    { name: "Digital subtraction angiography", why: "The reference standard, done in the catheter suite. It shows the small vessels of the foot that other scans blur, and treatment can follow in the same sitting." },
    { name: "MRI of the foot", why: "Answers whether infection has reached bone — osteomyelitis changes the treatment plan and the antibiotic duration." },
    { name: "Wound tissue culture", why: "A deep tissue sample identifies the true organism. Surface swabs mostly grow contaminants and misdirect antibiotics." },
  ],
  treatments: [
    { name: "Below-knee angioplasty", kind: "Endovascular", detail: "Balloon opening of the tibial and pedal arteries to bring direct flow to the wound bed. The central intervention in limb salvage." },
    { name: "Drug-coated balloon or stenting", kind: "Endovascular", detail: "Used above the knee where recoil or a long lesion makes plain ballooning insufficient." },
    { name: "Debridement", kind: "Surgery", detail: "Removal of dead tissue so the wound has a living edge to heal from. Repeated as needed, timed after flow is restored." },
    { name: "Targeted antibiotics", kind: "Medication", detail: "Guided by deep culture. Antibiotics cannot reach tissue that has no blood supply, which is why circulation is addressed first." },
    { name: "Offloading", kind: "Lifestyle", detail: "Total contact casting or offloading footwear removes pressure from the ulcer. Healing frequently fails for want of this alone." },
    { name: "Glycaemic and nutritional control", kind: "Lifestyle", detail: "Sugar control, protein intake and smoking cessation change healing rates measurably." },
    { name: "Minor amputation", kind: "Surgery", detail: "Removal of a single non-viable toe or ray, performed after revascularisation so the wound can close — a limb-preserving operation, not a failure." },
  ],
  approach: [
    "The first question is always circulation. No wound care plan is agreed before the arteries below the knee have been imaged.",
    "The target is direct flow to the angiosome — the specific territory of the foot in which the wound sits — not merely an improved pulse.",
    "Below-knee vessels are treated to the pedal arch where possible, using long balloons and low-profile wires.",
    "Procedures are done through a puncture, usually under local anaesthesia, and most patients go home the same or next day.",
    "Wound care, offloading, podiatry and diabetes control run in parallel; revascularisation alone does not close a wound.",
    "Amputation is considered only after the arterial tree has been assessed and treated.",
  ],
  procedures: ["angioplasty"],
  recovery: [
    { when: "Day 0", what: "Angioplasty through a small puncture. The foot usually feels warmer within hours. Bed rest for a few hours, then walking." },
    { when: "Week 1", what: "Debridement and dressing regimen begin against a now well-perfused wound bed. Antibiotics adjusted to culture." },
    { when: "Weeks 2 to 6", what: "Granulation tissue appears and the wound edge contracts. Offloading maintained without exception." },
    { when: "Months 2 to 4", what: "Most ulcers close in this window when flow has been restored and pressure removed." },
    { when: "Month 6", what: "Doppler review to confirm the treated segment remains open, and footwear reassessed." },
    { when: "Long term", what: "Daily foot inspection, annual vascular review, and immediate reporting of any new break in the skin." },
  ],
  prevention: [
    "Inspect both feet daily, including between the toes and the soles, using a mirror if needed",
    "Never walk barefoot, indoors or outdoors",
    "Have calluses trimmed by a podiatrist, not at home",
    "Wear properly fitted footwear and check inside shoes before wearing",
    "Keep HbA1c to the target agreed with your physician",
    "Stop smoking",
    "Have pulses and sensation checked at least once a year",
    "Report any new wound within days, not weeks",
  ],
  faqs: [
    { q: "Why won't my diabetic foot wound heal?", a: "Most often because the arteries supplying the foot are narrowed and the tissue is not receiving enough oxygen. Infection and pressure are common additional factors." },
    { q: "Can my foot be saved?", a: "In a large proportion of cases yes, if the blood supply can be restored before tissue loss becomes extensive. That question should be answered with an angiogram, not an opinion." },
    { q: "Is amputation the only option?", a: "It should be the last option. Below-knee angioplasty has changed what is salvageable, and a full vascular assessment should precede any amputation decision." },
    { q: "What is angioplasty in diabetic foot?", a: "A thin balloon is passed through a needle puncture into the leg arteries and inflated to reopen the blocked segments, restoring direct flow to the wound." },
    { q: "Is angioplasty painful?", a: "It is performed under local anaesthesia. Patients feel pressure rather than pain, and often report warmth in the foot during the case." },
    { q: "How long does the procedure take?", a: "Typically one to two hours, depending on how many vessels are blocked and how long the blockages are." },
    { q: "Will I be admitted?", a: "Usually one night, sometimes as a day case. Wound and infection status often decides this rather than the procedure itself." },
    { q: "What is the difference between poor circulation and infection?", a: "Infection produces redness, warmth, discharge and fever. Poor circulation produces coldness, pain at rest, blackening and a wound that simply does not progress. They frequently coexist." },
    { q: "Why is a Doppler done first?", a: "It is quick, painless and identifies whether there is arterial disease at all, and roughly at what level, before contrast studies are considered." },
    { q: "Why do I need CT angiography as well?", a: "Doppler shows there is a problem; CT angiography shows the exact anatomy needed to plan a route for the catheter." },
    { q: "Is contrast safe if my kidneys are weak?", a: "Contrast is used cautiously with hydration, minimal volume and sometimes carbon dioxide angiography instead. Kidney function is always checked first." },
    { q: "Can antibiotics alone heal the ulcer?", a: "Not if blood supply is inadequate — antibiotics travel in blood and cannot reach tissue that has none. Circulation must be addressed for antibiotics to work." },
    { q: "How long will the wound take to heal after angioplasty?", a: "Commonly six to sixteen weeks, depending on wound size, depth, infection and how consistently pressure is kept off it." },
    { q: "Will the artery block again?", a: "It can, particularly in diabetes and kidney disease. Follow-up Doppler, medication and risk factor control reduce the chance, and a repeat procedure is possible if needed." },
    { q: "Does smoking really matter at this stage?", a: "Enormously. Continued smoking is one of the strongest predictors of failed healing and repeat blockage." },
    { q: "What is offloading and why does it matter?", a: "It means removing weight from the ulcer with a cast or special footwear. A wound that is walked on each day cannot close, however good the circulation." },
    { q: "What is Charcot foot?", a: "Progressive collapse of the bones of the foot due to neuropathy, changing its shape and creating new pressure points. It requires immobilisation and specialist care." },
    { q: "Is a black toe always lost?", a: "Not always. If flow is restored early, the demarcation can stay limited and only a small portion may need removal." },
    { q: "How often should I have my feet checked?", a: "At least annually if you have no problems, and far more often if you have neuropathy, arterial disease or a previous ulcer." },
    { q: "Can this happen to my other foot?", a: "Yes. The disease process is systemic, so the opposite foot is examined and monitored as a matter of routine." },
  ],
  relatedConditions: ["peripheral-artery-disease", "critical-limb-ischemia", "venous-ulcer", "aorto-iliac-disease"],
  relatedSymptoms: ["Non-healing wound", "Black toe", "Cold foot", "Numbness in the feet", "Rest pain at night"],
};
