import type { Pillar } from "./types";

export const bph: Pillar = {
  slug: "enlarged-prostate",
  name: "Enlarged Prostate (BPH)",
  title: "Enlarged prostate",
  heroQuote: "I'm up four times a night.",
  heroLead:
    "An enlarged prostate squeezes the urinary channel until the bladder can no longer empty properly. Blocking the arteries that feed the gland makes it shrink from within — no catheter through the urethra, no cutting, and no effect on sexual function.",
  summary:
    "Weak stream, urgency and night-time urination from benign prostatic enlargement. Prostate artery embolization shrinks the gland through a pinhole, preserving sexual function.",

  symptoms: [
    "Getting up two or more times a night to pass urine",
    "A weak or interrupted urinary stream",
    "Difficulty starting urination",
    "Straining to pass urine",
    "A feeling the bladder has not emptied",
    "Urgency, sometimes with leakage",
    "Frequency during the day",
    "Dribbling at the end of urination",
    "In advanced cases, complete inability to pass urine",
  ],
  causes: [
    "Age-related benign growth of the prostate gland",
    "Hormonal changes, principally the effect of dihydrotestosterone on prostate tissue",
    "Enlargement of the transition zone compressing the urethra",
    "A median lobe growing into the bladder base",
    "Secondary bladder muscle changes from chronic obstruction",
  ],
  riskFactors: [
    "Age above 50",
    "Family history of prostate enlargement",
    "Obesity",
    "Type 2 diabetes",
    "Physical inactivity",
    "Metabolic syndrome",
  ],
  warningSigns: [
    "Complete inability to pass urine with a painful lower abdomen — acute retention, requiring urgent care",
    "Blood in the urine",
    "Recurrent urinary infections",
    "Fever with burning urination",
    "Rising creatinine, indicating the kidneys are being affected",
    "Bladder stones on imaging",
  ],
  diagnosis: [
    { step: "History", detail: "Symptom score, night-time frequency, previous retention or infections, medications, and the effect on daily life." },
    { step: "Clinical examination", detail: "Abdominal examination for a full bladder and digital rectal examination to assess prostate size, consistency and any nodularity." },
    { step: "Blood tests", detail: "PSA, kidney function and blood sugar. PSA is interpreted alongside gland size and rectal findings, not in isolation." },
    { step: "Imaging", detail: "Ultrasound for prostate volume and residual urine, uroflowmetry for stream rate, and MRI or CT angiography before embolization." },
  ],
  tests: [
    { name: "IPSS symptom score", why: "A standardised questionnaire that converts symptoms into a number, making it possible to measure whether treatment actually helped." },
    { name: "Uroflowmetry", why: "Measures the strength of the stream objectively, distinguishing true obstruction from an overactive bladder." },
    { name: "Post-void residual ultrasound", why: "Shows how much urine is left after passing water. A large residual indicates the bladder is failing to empty and raises the risk of infection and kidney damage." },
    { name: "Transabdominal or transrectal ultrasound", why: "Measures gland volume, which guides which treatments are appropriate and predicts response." },
    { name: "PSA", why: "Screens for prostate cancer, which can coexist and must be excluded before treating enlargement as benign." },
    { name: "Prostate MRI", why: "Assesses gland anatomy, the median lobe, and any suspicious area needing biopsy before intervention." },
    { name: "CT angiography of the pelvis", why: "Maps the prostatic arteries, which are small and variable. Planning this in advance shortens the procedure and reduces contrast use." },
  ],
  treatments: [
    { name: "Watchful waiting", kind: "Observation", detail: "Reasonable for mild symptoms, with fluid timing advice and annual review." },
    { name: "Alpha blockers", kind: "Medication", detail: "Relax the muscle of the prostate and bladder neck, improving flow within days. Side effects include dizziness and retrograde ejaculation." },
    { name: "5-alpha reductase inhibitors", kind: "Medication", detail: "Shrink the gland over months. They can reduce libido and affect erectile function in some men." },
    { name: "Prostate artery embolization", kind: "Endovascular", detail: "Particles delivered through a catheter block the prostatic arteries. The gland shrinks over weeks, symptoms improve, and sexual function is preserved." },
    { name: "TURP", kind: "Surgery", detail: "Endoscopic removal of obstructing tissue through the urethra. Highly effective, with retrograde ejaculation in most men and a longer recovery." },
    { name: "Laser enucleation", kind: "Surgery", detail: "A surgical alternative for very large glands, removing tissue with laser energy." },
    { name: "Catheterisation", kind: "Observation", detail: "A temporary measure in retention while definitive treatment is planned. Embolization can allow removal of a long-standing catheter." },
  ],
  approach: [
    "Cancer is excluded before enlargement is treated as benign — PSA, examination and MRI where indicated.",
    "Embolization is offered to men with moderate to severe symptoms, men who cannot tolerate or do not wish to take long-term medication, men in retention, and men unfit for or unwilling to accept surgery.",
    "CT angiography is used beforehand to map the prostatic artery origins, which vary considerably between patients.",
    "Access is through a single puncture at the wrist or groin under local anaesthesia; no instrument enters the urethra.",
    "Both sides are embolized with cone-beam guidance to confirm the target territory before particles are released.",
    "Preservation of ejaculatory and erectile function is treated as an outcome, not an afterthought.",
  ],
  procedures: ["prostate-embolization"],
  recovery: [
    { when: "Same day", what: "A few hours of observation, then discharge. Mild pelvic ache or burning on urination is common." },
    { when: "Days 1 to 5", what: "Post-embolization syndrome in some men — mild fever, frequency, a little blood in urine or semen. It settles with simple treatment." },
    { when: "Week 1 to 2", what: "Return to normal activity. Stream often begins to improve." },
    { when: "Month 1 to 3", what: "Main symptom improvement. Where a catheter was in place, removal is usually attempted within this window." },
    { when: "Month 6", what: "Ultrasound shows gland volume reduction and reduced residual urine; symptom score repeated." },
    { when: "Year 1 and beyond", what: "Sustained improvement in most patients; annual review with PSA and symptom score." },
  ],
  prevention: [
    "Limit fluids in the two hours before bed",
    "Reduce caffeine and alcohol, which irritate the bladder",
    "Do not delay passing urine for long periods",
    "Maintain a healthy weight and stay physically active",
    "Control diabetes",
    "Review medications such as decongestants that can worsen retention",
    "Have annual assessment once symptoms begin, rather than adapting to them",
  ],
  faqs: [
    { q: "What is BPH?", a: "Benign prostatic hyperplasia — a non-cancerous enlargement of the prostate that compresses the urinary channel and obstructs flow." },
    { q: "Is an enlarged prostate cancer?", a: "No, but the two can coexist. PSA, examination and sometimes MRI are used to exclude cancer before treating enlargement." },
    { q: "What is prostate artery embolization?", a: "A catheter procedure that blocks the arteries supplying the prostate, causing the gland to shrink and symptoms to improve over weeks." },
    { q: "Does anything go into the urethra?", a: "No. Access is through a small puncture at the wrist or groin, which is why the procedure is attractive to many men." },
    { q: "Will it affect my sexual function?", a: "Preservation of erectile and ejaculatory function is one of the main advantages of embolization over surgery, where retrograde ejaculation is common." },
    { q: "How long does it take?", a: "Usually one to two hours, depending on how the prostatic arteries arise on each side." },
    { q: "Is it done under general anaesthesia?", a: "No, local anaesthesia with light sedation is standard, and patients are awake throughout." },
    { q: "How soon will symptoms improve?", a: "Some men notice change within two weeks, but the main improvement occurs between one and three months." },
    { q: "How much does the prostate shrink?", a: "Typically twenty to forty percent of volume, though symptom relief correlates more with reduced congestion than with size alone." },
    { q: "Can it be done if I have a catheter?", a: "Yes, and it is one of the strongest indications. Many men become catheter-free within weeks." },
    { q: "What are the risks?", a: "Post-embolization syndrome with mild fever and urinary irritation, blood in urine or semen, temporary retention, and rarely non-target embolization causing bladder or rectal irritation." },
    { q: "How does it compare with TURP?", a: "TURP relieves obstruction more completely but requires anaesthesia, a hospital stay and usually causes retrograde ejaculation. Embolization is gentler with faster recovery and preserved ejaculation." },
    { q: "Can I stop my medication afterwards?", a: "Many men reduce or stop alpha blockers after a few months, guided by symptom score and flow measurement." },
    { q: "Is the improvement permanent?", a: "Results are durable in most men for years. A minority need repeat treatment or medication later." },
    { q: "Does prostate size decide the treatment?", a: "It is a major factor. Very large glands may favour embolization or enucleation over standard TURP." },
    { q: "Will my PSA change?", a: "PSA usually falls after embolization, in line with reduced gland volume. It continues to be monitored." },
    { q: "Why do I wake so often at night?", a: "Incomplete emptying leaves a small functional bladder capacity, and fluid mobilised from the legs at night increases urine production." },
    { q: "Is retention dangerous?", a: "Acute retention is painful and needs urgent catheterisation. Chronic retention can silently damage the kidneys, which is why residual volume is measured." },
    { q: "Do I need to stop blood thinners?", a: "Usually a brief adjustment is made, decided with your physician based on why you take them." },
    { q: "Who should not have embolization?", a: "Men with untreated prostate cancer, active urinary infection, or severely diseased pelvic arteries that cannot be safely navigated." },
  ],
  relatedConditions: ["enlarged-prostate", "uterine-fibroids"],
  relatedSymptoms: ["Night-time urination", "Weak urinary stream", "Urgency", "Incomplete emptying", "Urinary retention"],
};
