import type { Pillar } from "./types";

export const gangrene: Pillar = {
  slug: "gangrene",
  name: "Gangrene",
  title: "Gangrene",
  heroQuote: "My toe has turned black.",
  heroLead:
    "Gangrene is tissue that has died because its blood supply stopped. The blackened part will not return, but the line where death stops is decided by the circulation above it — and that circulation can often still be reopened.",
  summary:
    "Blackened, dying tissue from lost blood supply. Restoring flow by angioplasty limits the loss and frequently converts a major amputation into a minor one.",

  symptoms: [
    "Skin that has turned dark blue, brown or black",
    "A clear line between healthy and dead tissue",
    "Severe pain, followed by numbness once nerves die",
    "Coldness of the affected part",
    "Foul-smelling discharge when infection is present",
    "Skin that is shiny, tight and then breaks down",
    "Fever, rapid pulse or confusion when infection spreads to the bloodstream",
    "Crackling under the skin in gas gangrene — a surgical emergency",
  ],
  causes: [
    "Peripheral arterial disease — chronic narrowing that finally starves the tissue",
    "Acute arterial occlusion by clot or embolus",
    "Diabetes, combining arterial disease, neuropathy and infection",
    "Severe infection causing tissue destruction (wet gangrene)",
    "Clostridial infection of injured muscle (gas gangrene)",
    "Frostbite or crush injury",
    "Vasculitis or Buerger's disease",
    "Very low blood pressure with vasopressor use in critical illness",
  ],
  riskFactors: [
    "Diabetes with poor control",
    "Smoking",
    "Advanced peripheral arterial disease",
    "Kidney failure and dialysis",
    "Previous ulcer or amputation",
    "Immunosuppression",
    "Obesity",
    "Trauma or burns with contamination",
  ],
  warningSigns: [
    "Any blackening of skin — same-day medical assessment",
    "Spreading redness, swelling or foul odour, which indicates wet gangrene",
    "Fever, low blood pressure, confusion — sepsis, requiring emergency admission",
    "Crackling under the skin or rapidly advancing discoloration — surgical emergency",
    "Being offered an amputation without an arterial study — ask for vascular imaging first",
  ],
  diagnosis: [
    { step: "History", detail: "Onset and speed of change, pain pattern, diabetes, dialysis, smoking, and any preceding wound or injury." },
    { step: "Clinical examination", detail: "Extent and level of demarcation, pulses at every level, temperature change, and signs of spreading infection." },
    { step: "Blood tests", detail: "White cell count, CRP, lactate, blood culture, HbA1c and kidney function to grade infection and systemic effect." },
    { step: "Imaging", detail: "Urgent arterial Doppler and angiography to determine whether flow can be restored, plus X-ray or MRI for gas and bone involvement." },
  ],
  tests: [
    { name: "Arterial Doppler", why: "The fastest way to know whether the tissue above the gangrene still has flow — this decides whether salvage is possible at all." },
    { name: "CT angiography", why: "Shows the level and length of arterial blockage so a revascularisation route can be planned before surgery is contemplated." },
    { name: "Digital subtraction angiography", why: "The highest resolution view of the small foot vessels, allowing immediate angioplasty in the same session." },
    { name: "Plain X-ray", why: "Detects gas in the tissues and bone destruction from long-standing infection." },
    { name: "MRI", why: "Defines how deep the dead tissue extends and whether bone is infected, guiding the level of any debridement." },
    { name: "Deep tissue culture", why: "Identifies the true organisms so antibiotics are targeted rather than broad and ineffective." },
  ],
  treatments: [
    { name: "Revascularisation by angioplasty", kind: "Endovascular", detail: "Reopening the arteries above the dead tissue so the demarcation stops advancing and the wound can heal after debridement." },
    { name: "Catheter-directed thrombolysis", kind: "Endovascular", detail: "Used in acute occlusion, dissolving fresh clot directly at the blockage over hours." },
    { name: "Debridement", kind: "Surgery", detail: "Removal of dead tissue. In wet gangrene it is urgent; in dry gangrene it follows revascularisation." },
    { name: "Intravenous antibiotics", kind: "Medication", detail: "Essential in wet and gas gangrene, guided by culture and continued according to depth of infection." },
    { name: "Minor amputation", kind: "Surgery", detail: "Removal of a toe or ray after flow is restored, preserving a functional weight-bearing foot." },
    { name: "Major amputation", kind: "Surgery", detail: "Reserved for irreversible extensive tissue death or overwhelming sepsis, when the limb can no longer be saved." },
    { name: "Glycaemic and nutritional support", kind: "Lifestyle", detail: "Sugar control, protein and smoking cessation determine whether the surgical wound will heal." },
  ],
  approach: [
    "The first question is not how much to remove, but how much blood can be returned to the tissue above it.",
    "Angiography is arranged urgently. Dry gangrene with a stable line is given the chance of revascularisation before any amputation level is chosen.",
    "Wet gangrene and sepsis are different — infection is drained and controlled first, with revascularisation immediately after.",
    "Below-knee and pedal vessels are treated to bring direct flow into the affected angiosome.",
    "Amputation, when necessary, is planned at the lowest level that will heal, informed by post-procedure perfusion rather than by appearance alone.",
    "The opposite limb is assessed at the same admission, since it is usually at risk too.",
  ],
  procedures: ["angioplasty", "thrombectomy"],
  recovery: [
    { when: "Day 0 to 1", what: "Stabilisation, antibiotics if infected, and angiography with angioplasty where flow can be restored." },
    { when: "Days 2 to 7", what: "Demarcation stabilises. Debridement or minor amputation performed on a perfused wound bed." },
    { when: "Weeks 2 to 6", what: "Wound care, offloading and nutrition. Granulation appears where circulation has improved." },
    { when: "Months 2 to 4", what: "Wound closure in most salvaged limbs. Fitting of protective or custom footwear." },
    { when: "Month 6", what: "Doppler review of the treated segment and assessment of the opposite limb." },
    { when: "Long term", what: "Daily inspection, risk factor control, and immediate review of any new skin break." },
  ],
  prevention: [
    "Treat peripheral arterial disease before tissue loss begins",
    "Stop smoking",
    "Inspect the feet daily if diabetic, and never walk barefoot",
    "Seek review for any wound present beyond two weeks",
    "Keep HbA1c, blood pressure and cholesterol at target",
    "Attend regularly for podiatry and vascular review",
    "Do not treat a black spot on a toe as a bruise",
  ],
  faqs: [
    { q: "What is gangrene?", a: "Death of body tissue caused by loss of blood supply, infection, or both. It most commonly affects toes, feet and fingers." },
    { q: "What is the difference between dry and wet gangrene?", a: "Dry gangrene is caused purely by lack of blood supply and is usually slow with a clear line. Wet gangrene involves infection, spreads quickly and is far more dangerous." },
    { q: "Is gangrene always treated by amputation?", a: "No. Dead tissue must be removed, but restoring blood flow first often limits removal to a toe rather than the leg." },
    { q: "Can a black toe recover?", a: "The blackened tissue itself will not, but revascularisation can stop the process advancing and allow the surrounding tissue to heal after minor removal." },
    { q: "How urgent is gangrene?", a: "Dry gangrene requires assessment within days. Wet or gas gangrene requires emergency admission the same hour." },
    { q: "Why is angiography needed before amputation?", a: "It shows whether the arteries can be reopened. Amputating without knowing this risks operating at an unnecessarily high level, or a wound that will not heal." },
    { q: "Does angioplasty help once tissue is already dead?", a: "Yes — it protects what is still alive, stops the line advancing and gives the surgical wound the blood supply it needs to close." },
    { q: "What is gas gangrene?", a: "Rapidly spreading infection producing gas in the tissues, usually after contaminated injury. It is a surgical emergency with a high mortality if delayed." },
    { q: "Does gangrene hurt?", a: "It is intensely painful initially. Pain may then disappear as the nerves die, which patients sometimes mistake for improvement." },
    { q: "Can antibiotics alone treat gangrene?", a: "No. Antibiotics control infection but cannot revive dead tissue, and cannot reach tissue with no blood supply." },
    { q: "Is gangrene contagious?", a: "The tissue death is not, though the infections that cause wet gangrene require careful wound hygiene." },
    { q: "What causes gangrene in diabetes?", a: "A combination of narrowed small arteries, loss of sensation allowing unnoticed injury, and impaired resistance to infection." },
    { q: "Can smoking cause gangrene?", a: "Smoking is a major driver of the arterial disease that leads to it, and in Buerger's disease it is the direct cause." },
    { q: "How long does treatment take?", a: "Revascularisation is a single procedure of one to two hours; healing of the wound afterwards usually takes weeks to months." },
    { q: "What is demarcation?", a: "The visible boundary between dead and living tissue. A stable, sharp line suggests the process has halted." },
    { q: "Will I be able to walk after a toe amputation?", a: "Usually yes, often with modified footwear. Preserving the heel and forefoot balance is the goal of a low-level amputation." },
    { q: "Can gangrene recur?", a: "Yes, if the underlying arterial disease and risk factors are not controlled, or if a new wound goes unnoticed." },
    { q: "Does dialysis increase the risk?", a: "Considerably. Dialysis patients have heavily calcified vessels and impaired healing, and need earlier vascular assessment." },
    { q: "Is hyperbaric oxygen useful?", a: "It is an adjunct in selected infected wounds, but it cannot substitute for restoring arterial flow." },
    { q: "What should I do the day I notice blackening?", a: "Keep the area clean and dry, do not apply heat or cut anything, and seek vascular assessment the same day." },
  ],
  relatedConditions: ["critical-limb-ischemia", "diabetic-foot", "peripheral-artery-disease"],
  relatedSymptoms: ["Black toe", "Non-healing wound", "Foul smelling wound", "Cold painful foot", "Rest pain"],
};
