import type { Pillar } from "./types";

export const kneeOsteoarthritis: Pillar = {
  slug: "knee-osteoarthritis",
  name: "Knee Osteoarthritis",
  title: "Knee osteoarthritis",
  heroQuote: "My knee hurts, but I don't want a replacement.",
  heroLead:
    "In an arthritic knee, the lining grows an abnormal network of tiny new arteries, and pain nerves grow along with them. Blocking those abnormal vessels through a pinhole in the groin can reduce pain for years, without replacing the joint.",
  summary:
    "Persistent knee pain from osteoarthritis. Genicular artery embolization reduces pain by blocking the abnormal vessels that feed inflammation, without joint replacement.",

  symptoms: [
    "Pain on the inner side of the knee, worse on activity",
    "Morning stiffness that eases within half an hour",
    "Pain climbing or descending stairs",
    "Swelling after use",
    "Grinding or clicking on movement",
    "Difficulty squatting or kneeling",
    "Night pain that disturbs sleep",
    "Giving way or a feeling of instability",
    "Reduced walking distance",
  ],
  causes: [
    "Age-related cartilage wear",
    "Previous meniscal or ligament injury",
    "Previous fracture involving the joint",
    "Malalignment — bow legs or knock knees concentrating load",
    "Obesity increasing joint loading",
    "Inflammatory arthritis affecting the joint lining",
    "Occupational squatting and kneeling over many years",
  ],
  riskFactors: [
    "Age above 50",
    "Female sex, particularly after menopause",
    "Obesity",
    "Previous knee injury or surgery",
    "Family history of osteoarthritis",
    "Occupations with heavy lifting or prolonged kneeling",
    "Muscle weakness around the knee",
  ],
  warningSigns: [
    "A hot, red, acutely swollen knee with fever — infection must be excluded urgently",
    "Sudden locking of the knee, suggesting a mechanical block",
    "Rapidly progressive pain and deformity over weeks",
    "Night pain unrelated to activity, alongside weight loss",
    "Loss of the ability to straighten the leg",
  ],
  diagnosis: [
    { step: "History", detail: "Pain pattern and location, walking distance, stairs, night pain, previous injury, and what treatments have already failed." },
    { step: "Clinical examination", detail: "Alignment, effusion, range of movement, joint-line tenderness, ligament stability and muscle bulk." },
    { step: "Blood tests", detail: "Usually normal. Inflammatory markers and uric acid are checked when inflammatory arthritis or gout is a possibility." },
    { step: "Imaging", detail: "Weight-bearing X-rays grade the joint space; MRI assesses cartilage, meniscus and synovitis when the picture is unclear or before intervention." },
  ],
  tests: [
    { name: "Weight-bearing knee X-ray", why: "Standing films show the true joint space. A knee that looks acceptable lying down can show bone-on-bone contact when loaded." },
    { name: "MRI of the knee", why: "Shows cartilage loss, meniscal tears, bone marrow oedema and synovitis — the inflamed lining that embolization targets." },
    { name: "Ultrasound of the knee", why: "Confirms effusion and synovial thickening, and guides injection when one is planned." },
    { name: "Inflammatory blood markers", why: "Separate osteoarthritis from rheumatoid or septic arthritis, which need completely different treatment." },
    { name: "Joint aspiration", why: "Performed when infection or crystal arthritis is suspected. The fluid analysis is definitive." },
    { name: "Angiographic assessment", why: "At the time of embolization, contrast shows the abnormal hypervascular blush in the joint lining — confirming the pain generator that will be treated." },
  ],
  treatments: [
    { name: "Exercise and physiotherapy", kind: "Lifestyle", detail: "Quadriceps strengthening reduces pain and slows functional decline. It remains first-line and underused." },
    { name: "Weight reduction", kind: "Lifestyle", detail: "Every kilogram lost removes several kilograms of load from the knee during walking." },
    { name: "Analgesics and anti-inflammatories", kind: "Medication", detail: "Effective for flares; long-term use is limited by stomach, kidney and cardiac side effects." },
    { name: "Intra-articular steroid injection", kind: "Medication", detail: "Reliable short-term relief measured in weeks to a few months, repeatable only a limited number of times." },
    { name: "Hyaluronic acid injection", kind: "Medication", detail: "Variable benefit; some patients report improvement over several months." },
    { name: "Genicular artery embolization", kind: "Endovascular", detail: "Tiny particles injected through a catheter block the abnormal arteries supplying the inflamed lining, reducing pain over weeks to months. Day-care, through a pinhole." },
    { name: "Genicular nerve ablation", kind: "Ablation", detail: "Radiofrequency interruption of the sensory nerves carrying pain from the joint, used where pain relief rather than disease modification is the goal." },
    { name: "Knee replacement", kind: "Surgery", detail: "The definitive treatment for end-stage arthritis with structural collapse. Embolization does not preclude it later." },
  ],
  approach: [
    "Embolization is offered for mild to moderate osteoarthritis with pain out of proportion to the X-ray, where conservative measures have failed and joint replacement is unwanted or not yet appropriate.",
    "MRI is reviewed for synovitis — the inflamed, hypervascular lining is the target, and its presence predicts response.",
    "Access is a 2 mm puncture at the groin or wrist under local anaesthesia.",
    "Each genicular artery is selectively catheterised and the abnormal blush embolized with carefully sized particles, sparing the normal supply.",
    "Skin and nerve territories are checked before embolizing to avoid non-target injury.",
    "Patients walk within hours and go home the same day; relief builds progressively rather than instantly.",
  ],
  procedures: ["genicular-artery-embolization", "genicular-nerve-ablation"],
  recovery: [
    { when: "Same day", what: "Two to four hours of bed rest, then walking. Discharge the same evening in most cases." },
    { when: "Days 1 to 3", what: "Mild ache and occasional transient skin discoloration over the knee. Normal walking resumed." },
    { when: "Week 1 to 2", what: "Return to routine activity and physiotherapy. Early pain reduction is often noticeable." },
    { when: "Month 1 to 3", what: "The main improvement window. Night pain and stair pain usually improve first." },
    { when: "Month 6", what: "Assessment of pain score and function. Physiotherapy continues to consolidate the gain." },
    { when: "Year 1 to 2", what: "Benefit is sustained in most responders. The procedure can be repeated, and does not prevent later joint replacement." },
  ],
  prevention: [
    "Maintain a healthy body weight",
    "Strengthen the quadriceps and hip muscles regularly",
    "Choose low-impact exercise — cycling, swimming, brisk walking",
    "Avoid prolonged squatting and kneeling where possible",
    "Treat knee injuries properly rather than working through them",
    "Use supportive footwear",
    "Keep moving during flares; complete rest weakens the joint further",
  ],
  faqs: [
    { q: "What is genicular artery embolization?", a: "A catheter procedure that blocks the abnormal small arteries feeding the inflamed lining of an arthritic knee, reducing pain without operating on the joint." },
    { q: "Does it cure arthritis?", a: "No. It treats the pain generated by inflammation and abnormal vessels. The cartilage damage remains." },
    { q: "Who is a good candidate?", a: "Patients with mild to moderate osteoarthritis, persistent pain despite physiotherapy and injections, and who are not ready for or not suitable for joint replacement." },
    { q: "Who is not suitable?", a: "End-stage bone-on-bone arthritis with deformity, active infection, or severe peripheral arterial disease in the leg." },
    { q: "How is it performed?", a: "Through a small puncture at the groin or wrist under local anaesthesia, using X-ray guidance to reach the knee arteries. It takes about an hour." },
    { q: "Is it painful?", a: "The procedure itself is not. Some patients feel warmth or ache in the knee during embolization, which settles quickly." },
    { q: "When will I feel better?", a: "Some improvement within days, but the main benefit builds over four to twelve weeks." },
    { q: "How long does the relief last?", a: "Published series report meaningful pain reduction sustained at one to two years in most responders." },
    { q: "Can it be repeated?", a: "Yes, if pain returns and imaging shows recurrent abnormal vessels." },
    { q: "Will it stop me having a knee replacement later?", a: "No. It does not damage the joint or complicate subsequent surgery." },
    { q: "What are the risks?", a: "Temporary skin discoloration or small patches of skin irritation, transient knee ache, puncture site bruising, and rarely non-target embolization. It is generally well tolerated." },
    { q: "Is there radiation involved?", a: "Yes, X-ray guidance is used, with dose kept as low as achievable for the case." },
    { q: "How is this different from nerve ablation?", a: "Embolization reduces the inflammation driving pain; nerve ablation interrupts the nerves carrying the pain signal. They can be complementary." },
    { q: "Do steroid injections work better?", a: "Steroids act faster but wear off in weeks to months and cannot be repeated indefinitely. Embolization is slower to act and longer lasting." },
    { q: "Do I still need physiotherapy?", a: "Yes. Muscle strength determines function, and the pain relief is what makes effective physiotherapy possible." },
    { q: "Will I be admitted overnight?", a: "Usually not. It is a day-care procedure with a few hours of observation." },
    { q: "Can both knees be treated?", a: "Yes, usually in separate sessions a few weeks apart." },
    { q: "Does obesity affect the outcome?", a: "Weight strongly affects knee loading and long-term outcome, so weight management is part of the treatment plan." },
    { q: "Is MRI necessary before the procedure?", a: "It is strongly preferred, as it confirms synovitis and excludes other causes of pain such as a large meniscal tear." },
    { q: "Is this an established treatment?", a: "It is an established minimally invasive option supported by a growing body of published evidence, offered in selected patients rather than to everyone." },
  ],
  relatedConditions: ["chronic-knee-pain", "peripheral-artery-disease"],
  relatedSymptoms: ["Knee pain on stairs", "Morning stiffness", "Knee swelling", "Night knee pain", "Difficulty squatting"],
};
