import type { Pillar } from "./types";

export const liverTumours: Pillar = {
  slug: "liver-tumours",
  name: "Liver Tumours",
  title: "Liver tumours",
  heroQuote: "They said surgery isn't possible.",
  heroLead:
    "Liver tumours draw almost all their blood from the hepatic artery, while the healthy liver lives mainly on the portal vein. That difference is a treatment. A catheter can deliver chemotherapy or radiation into the tumour's own artery, or a needle can destroy it with heat, while the rest of the liver continues working.",
  summary:
    "Primary and secondary liver tumours treated through the artery or with a needle — TACE, radioembolization and microwave ablation — targeting the tumour while sparing healthy liver.",

  symptoms: [
    "Often no symptoms at all in early tumours, found on surveillance scanning",
    "Discomfort or fullness in the upper right abdomen",
    "Unexplained weight loss",
    "Loss of appetite and early fullness after eating",
    "Fatigue",
    "Jaundice — yellowing of eyes and skin",
    "Abdominal swelling from fluid (ascites)",
    "Nausea",
    "Fever without obvious infection",
  ],
  causes: [
    "Hepatocellular carcinoma arising in a cirrhotic liver",
    "Chronic hepatitis B or C infection",
    "Alcohol-related liver disease",
    "Non-alcoholic fatty liver disease with fibrosis",
    "Metastases from colorectal, breast, neuroendocrine or other primary cancers",
    "Cholangiocarcinoma arising from the bile ducts",
    "Aflatoxin exposure in contaminated food, in some regions",
    "Haemochromatosis and other inherited liver disease",
  ],
  riskFactors: [
    "Cirrhosis of any cause",
    "Chronic hepatitis B or C",
    "Heavy alcohol use",
    "Type 2 diabetes and obesity with fatty liver",
    "Male sex",
    "Age above 50",
    "Family history of liver cancer",
    "A known primary cancer elsewhere, for secondary tumours",
  ],
  warningSigns: [
    "New jaundice",
    "Rapidly increasing abdominal swelling",
    "Vomiting blood or passing black stool — variceal bleeding, an emergency",
    "Confusion or excessive drowsiness, indicating liver decompensation",
    "Severe abdominal pain with fever",
    "Unexplained weight loss over weeks",
  ],
  diagnosis: [
    { step: "History", detail: "Hepatitis status, alcohol intake, known cirrhosis, previous cancer, weight loss and current liver medication." },
    { step: "Clinical examination", detail: "Liver size and texture, splenomegaly, ascites, jaundice and signs of chronic liver disease." },
    { step: "Blood tests", detail: "Liver function, albumin, bilirubin, INR, platelet count, alpha-fetoprotein and hepatitis serology. These determine liver reserve and therefore what treatment is safe." },
    { step: "Imaging", detail: "Multiphase CT or MRI with contrast is diagnostic for hepatocellular carcinoma in a cirrhotic liver; biopsy is reserved for uncertain cases." },
  ],
  tests: [
    { name: "Triple-phase CT of the liver", why: "Images the liver in arterial, portal and delayed phases. The pattern of early enhancement and washout is diagnostic for hepatocellular carcinoma without needing a biopsy." },
    { name: "MRI with liver-specific contrast", why: "The most sensitive test for small lesions and for telling regenerative nodules in cirrhosis from true tumour." },
    { name: "Alpha-fetoprotein", why: "A tumour marker used alongside imaging for diagnosis and for tracking response, though it is normal in a substantial proportion of tumours." },
    { name: "Liver function and Child-Pugh scoring", why: "Determines how much treatment the liver can tolerate. A tumour that is technically treatable may not be safely treatable in a failing liver." },
    { name: "Ultrasound surveillance", why: "Six-monthly ultrasound in cirrhosis is what finds these tumours while they are still small and curable." },
    { name: "Biopsy", why: "Used when imaging is indeterminate or when the tumour is not in a cirrhotic liver, to establish tissue diagnosis." },
    { name: "PET-CT", why: "Mainly for metastatic disease, to establish whether the liver is the only site involved before local treatment is planned." },
  ],
  treatments: [
    { name: "Transarterial chemoembolization (TACE)", kind: "Endovascular", detail: "Chemotherapy delivered directly into the tumour's feeding artery, followed by blocking that artery so the drug stays concentrated in the tumour." },
    { name: "Transarterial radioembolization (TARE)", kind: "Endovascular", detail: "Radioactive microspheres delivered into the tumour's arterial supply, giving high local radiation dose with minimal effect on the rest of the liver." },
    { name: "Microwave ablation", kind: "Ablation", detail: "A needle placed into the tumour under imaging guidance destroys it with heat. For small tumours it approaches surgical cure rates." },
    { name: "Radiofrequency ablation", kind: "Ablation", detail: "The same needle-based principle using radiofrequency energy, well suited to small lesions away from major vessels." },
    { name: "Portal vein embolization", kind: "Endovascular", detail: "Blocking the portal branch to the diseased side so the healthy side grows, making major surgery possible where it otherwise would not be." },
    { name: "Surgical resection", kind: "Surgery", detail: "Removal of the tumour-bearing segment, appropriate when liver function and tumour position allow." },
    { name: "Systemic therapy", kind: "Medication", detail: "Targeted agents and immunotherapy for advanced disease, increasingly combined with arterial treatments." },
    { name: "Transplantation", kind: "Surgery", detail: "Treats both the tumour and the underlying cirrhosis in selected patients within recognised criteria." },
  ],
  approach: [
    "Every case is discussed in a multidisciplinary setting — hepatology, surgery, oncology and interventional radiology. No single specialty owns liver cancer.",
    "Liver reserve is assessed before technique: the goal is treating the tumour without pushing the liver into failure.",
    "Arterial anatomy is mapped in detail, including variant supply, because incomplete arterial coverage means incomplete treatment.",
    "Superselective catheterisation is used so the embolic or radioactive load reaches the tumour and not the surrounding parenchyma.",
    "For radioembolization, a planning study with mapping and shunt assessment always precedes treatment.",
    "Ablation and arterial treatment are combined where the lesion size or position makes either alone insufficient.",
    "Response is measured by enhancement on imaging, not by size alone — a treated tumour may not shrink but should stop taking up contrast.",
  ],
  procedures: ["tace", "microwave-ablation", "embolization"],
  recovery: [
    { when: "Day 0", what: "TACE is performed through a groin or wrist puncture. Overnight admission is usual, with pain and nausea managed proactively." },
    { when: "Days 1 to 5", what: "Post-embolization syndrome — fever, right upper abdominal pain, nausea and fatigue — is expected and settles with supportive treatment." },
    { when: "Week 1 to 2", what: "Return to routine activity. Liver function tests repeated to confirm recovery." },
    { when: "Month 1", what: "Contrast CT or MRI assesses response by loss of enhancement in the treated tumour." },
    { when: "Month 3", what: "Decision on whether a further session is needed, based on residual viable tumour." },
    { when: "Ongoing", what: "Three-monthly imaging and tumour markers, with continued treatment of the underlying liver disease." },
  ],
  prevention: [
    "Vaccinate against hepatitis B",
    "Test for and treat hepatitis B and C — treatment substantially reduces cancer risk",
    "Stop alcohol entirely if there is any liver fibrosis",
    "Manage weight, diabetes and cholesterol to limit fatty liver progression",
    "Attend six-monthly ultrasound surveillance if you have cirrhosis — this is what finds curable tumours",
    "Avoid unnecessary hepatotoxic medications and unregulated supplements",
    "Treat iron overload and other inherited liver disease actively",
  ],
  faqs: [
    { q: "What is TACE?", a: "Transarterial chemoembolization — chemotherapy is delivered directly into the artery feeding the tumour and that artery is then blocked, trapping the drug inside the tumour." },
    { q: "Why does treating the artery work?", a: "Liver tumours draw nearly all their blood from the hepatic artery, while normal liver is supplied mainly by the portal vein. The artery can therefore be targeted with relative sparing of healthy tissue." },
    { q: "Is TACE a cure?", a: "It is usually a disease-control treatment that can be repeated, sometimes used to bridge patients to transplantation. Small tumours treated with ablation can be cured." },
    { q: "What is microwave ablation?", a: "A needle is placed into the tumour under ultrasound or CT guidance and heat destroys it. For tumours under about three centimetres, results approach those of surgery." },
    { q: "How is radioembolization different from TACE?", a: "Radioembolization delivers radioactive microspheres rather than chemotherapy and causes less arterial blockage, so it is often preferred in portal vein involvement or larger tumours." },
    { q: "Will I lose my hair with TACE?", a: "Generally no. The chemotherapy is concentrated in the liver, so systemic side effects are far less than with intravenous chemotherapy." },
    { q: "How painful is the procedure?", a: "The catheter work itself is not painful. The following days can bring right upper abdominal pain and fever, which is expected and managed with medication." },
    { q: "How long is the hospital stay?", a: "Usually one night for TACE, and often day-care or one night for ablation." },
    { q: "How many sessions will I need?", a: "It depends on tumour number, size and response. Two to four sessions over several months is common." },
    { q: "What is post-embolization syndrome?", a: "Fever, pain, nausea and fatigue for a few days after treatment, caused by the tumour dying. It is expected, not a complication." },
    { q: "How will you know if it worked?", a: "Follow-up CT or MRI looks for loss of contrast enhancement in the tumour. A treated tumour may not shrink immediately but should stop enhancing." },
    { q: "Can these treatments be done if I have cirrhosis?", a: "Yes, and most patients treated do have cirrhosis. Liver reserve is assessed carefully first, because treatment must not push the liver into failure." },
    { q: "Can liver metastases be treated this way?", a: "Yes. Colorectal and neuroendocrine metastases in particular respond to arterial and ablative treatments, usually alongside systemic therapy." },
    { q: "Will I still need chemotherapy?", a: "Often yes for metastatic disease. Local treatment complements systemic therapy rather than replacing it." },
    { q: "Is surgery better?", a: "Resection or transplantation offers cure when liver function and tumour position allow. Many patients are not candidates, and that is where these treatments are used." },
    { q: "What is portal vein embolization?", a: "Blocking the portal supply to the diseased side of the liver so the other side enlarges, making major surgery possible in patients who otherwise could not tolerate it." },
    { q: "Are the treatments repeatable?", a: "Yes. TACE in particular is designed to be repeated according to imaging response and liver function." },
    { q: "What are the main risks?", a: "Liver function deterioration, infection or abscess, gallbladder inflammation, non-target embolization and contrast effects on the kidneys." },
    { q: "How often should I be scanned afterwards?", a: "Typically at one month, then every three months, with tumour markers alongside." },
    { q: "Does surveillance really matter in cirrhosis?", a: "It is the single most important factor. Tumours found on six-monthly ultrasound are far more often small enough for curative treatment." },
  ],
  relatedConditions: ["hepatocellular-carcinoma", "portal-hypertension", "variceal-bleeding", "gi-bleeding"],
  relatedSymptoms: ["Upper abdominal discomfort", "Jaundice", "Unexplained weight loss", "Abdominal swelling", "Fatigue"],
};
