import type { Pillar } from "./types";

export const pad: Pillar = {
  slug: "peripheral-arterial-disease",
  name: "Peripheral Arterial Disease",
  title: "Peripheral arterial disease",
  heroQuote: "My legs hurt when I walk.",
  heroLead:
    "Plaque narrows the arteries of the leg until the muscle cannot get the oxygen it needs to move. It begins as pain after a set distance, and ends — if untreated — as pain at rest and tissue loss. The narrowing can be reopened from inside the artery.",
  summary:
    "Cramping leg pain on walking, caused by narrowed leg arteries. Angioplasty and stenting reopen the artery through a puncture and restore walking distance.",

  symptoms: [
    "Cramping pain in the calf, thigh or buttock after walking a predictable distance",
    "Pain that stops within minutes of standing still",
    "Walking distance that shortens month by month",
    "Coldness or pallor of one foot",
    "Pain in the forefoot at night, eased by hanging the leg over the bed",
    "Loss of hair on the lower leg, shiny tight skin",
    "Slow-growing, thickened toenails",
    "Wounds on the foot that do not heal",
    "Erectile dysfunction, when the disease involves the aorto-iliac segment",
  ],
  causes: [
    "Atherosclerosis — cholesterol plaque building within the artery wall",
    "Thrombosis on an existing plaque, causing sudden worsening",
    "Embolism from the heart or a proximal aneurysm",
    "Arterial dissection",
    "Inflammatory arteritis, notably Buerger's disease in young smokers",
    "Radiation-induced arterial narrowing after previous treatment",
  ],
  riskFactors: [
    "Smoking — the strongest modifiable risk factor for leg arteries",
    "Diabetes",
    "High blood pressure",
    "High cholesterol",
    "Age over 50",
    "Chronic kidney disease",
    "Known coronary or carotid artery disease",
    "Family history of vascular disease",
  ],
  warningSigns: [
    "Pain in the foot at rest or at night — the disease has progressed beyond exercise limitation",
    "Any non-healing wound or ulcer on the foot",
    "Blackening of a toe",
    "A suddenly cold, pale, painful and numb leg — an emergency requiring immediate assessment",
    "Walking distance falling rapidly over weeks rather than years",
  ],
  diagnosis: [
    { step: "History", detail: "Claudication distance, whether it is reproducible, rest pain, wounds, smoking history and cardiac symptoms." },
    { step: "Clinical examination", detail: "Palpation of femoral, popliteal, dorsalis pedis and posterior tibial pulses; skin temperature; capillary refill; auscultation for bruits." },
    { step: "Blood tests", detail: "Lipid profile, HbA1c, kidney function and haemoglobin — all shape both risk and the safety of contrast imaging." },
    { step: "Imaging", detail: "Ankle-brachial index and Doppler first; CT angiography to plan; catheter angiography when treatment is intended in the same sitting." },
  ],
  tests: [
    { name: "Ankle-brachial index", why: "Compares ankle to arm pressure. A simple number that confirms the diagnosis, grades severity and can be repeated to track progress." },
    { name: "Arterial Doppler ultrasound", why: "Locates the level of narrowing and shows how the waveform changes across it, without radiation or contrast." },
    { name: "Treadmill exercise test", why: "Used when resting pressures look normal but symptoms are typical. Pressures are measured after walking, when the deficit reveals itself." },
    { name: "CT angiography", why: "A single scan mapping aorta to foot, showing calcification, length of blockage and run-off — the anatomy on which the treatment plan rests." },
    { name: "MR angiography", why: "An alternative when kidney function or contrast allergy makes CT unsuitable." },
    { name: "Digital subtraction angiography", why: "Performed in the catheter suite with the highest resolution for below-knee vessels, allowing diagnosis and treatment in one visit." },
  ],
  treatments: [
    { name: "Supervised exercise therapy", kind: "Lifestyle", detail: "Structured walking to the point of pain, repeatedly, develops collateral flow. For mild claudication it rivals intervention." },
    { name: "Smoking cessation", kind: "Lifestyle", detail: "The single most effective measure. It changes both symptoms and the durability of any procedure performed." },
    { name: "Statins and antiplatelets", kind: "Medication", detail: "Reduce plaque progression and the risk of heart attack and stroke, which are the commonest causes of death in this disease." },
    { name: "Cilostazol", kind: "Medication", detail: "Improves walking distance in selected patients without heart failure." },
    { name: "Balloon angioplasty", kind: "Endovascular", detail: "The narrowed segment is crossed with a wire and dilated with a balloon through a small puncture." },
    { name: "Stenting", kind: "Endovascular", detail: "A mesh scaffold holds the artery open where the vessel recoils or dissects after ballooning." },
    { name: "Drug-coated balloon", kind: "Endovascular", detail: "Delivers medication to the vessel wall to slow re-narrowing, particularly in the thigh artery." },
    { name: "Atherectomy", kind: "Endovascular", detail: "Removal or modification of heavily calcified plaque so the vessel can be dilated properly." },
    { name: "Bypass surgery", kind: "Surgery", detail: "Reserved for very long occlusions or after endovascular options have been exhausted." },
  ],
  approach: [
    "Claudication and limb-threatening ischemia are treated as different problems: the first is about quality of life, the second about saving a limb.",
    "Every patient is assessed for heart and carotid disease at the same time — leg arteries rarely narrow in isolation.",
    "Endovascular treatment is preferred first, preserving the vein for any future bypass.",
    "Access is through a puncture at the groin, wrist or occasionally the foot artery, under local anaesthesia.",
    "In long occlusions, both antegrade and retrograde approaches are used to cross the lesion.",
    "Medical therapy is not optional background — statins, antiplatelets and smoking cessation are part of the procedure's success.",
  ],
  procedures: ["angioplasty"],
  recovery: [
    { when: "Procedure: Day 0", what: "Angioplasty via puncture. Bed rest for a few hours, then walking. Most patients notice warmth returning." },
    { when: "Day 1", what: "Discharged and walking. Puncture site checked and antiplatelet regimen started or adjusted." },
    { when: "1 Week", what: "Return to light activity and routine lifestyle resume. Walking distance usually improves noticeably." },
    { when: "1 Month", what: "Follow-up imaging and normal life. Ankle-brachial index repeated to document the gain." },
  ],

  prevention: [
    "Stop smoking entirely",
    "Walk daily, pushing to near-maximal pain then resting and repeating",
    "Take statin and antiplatelet therapy without interruption",
    "Keep blood pressure and HbA1c at target",
    "Inspect the feet daily if you also have diabetes",
    "Report any fall in walking distance rather than adapting your life around it",
    "Maintain a healthy weight and a diet low in saturated fat",
  ],
  faqs: [
    { q: "What is peripheral arterial disease?", a: "Narrowing of the arteries supplying the limbs, usually by cholesterol plaque, reducing blood flow to the muscles and skin." },
    { q: "What is claudication?", a: "Reproducible cramping pain in the leg muscles brought on by walking a certain distance and relieved by rest. It is the classic symptom of PAD." },
    { q: "Is leg pain on walking always PAD?", a: "No. Spinal canal narrowing, arthritis and venous disease can mimic it. The pattern of relief and the ankle-brachial index usually separate them." },
    { q: "Will I lose my leg?", a: "Most people with claudication never do. The risk rises sharply once rest pain or tissue loss appears, which is why those symptoms need urgent assessment." },
    { q: "Can PAD be reversed?", a: "The plaque itself does not disappear, but flow can be restored by angioplasty and further progression slowed substantially by medication and stopping smoking." },
    { q: "Is walking safe when it causes pain?", a: "Yes, and it is therapeutic. Structured walking to the point of pain encourages collateral vessels to develop." },
    { q: "What is the ankle-brachial index?", a: "The ratio of ankle to arm blood pressure. Below 0.9 indicates arterial disease; below 0.4 indicates severe disease." },
    { q: "Why is my ABI normal if my arteries are calcified?", a: "In diabetes and kidney disease, calcified vessels resist compression and give falsely high readings. Toe pressures are used instead." },
    { q: "What does angioplasty involve?", a: "A needle puncture, a wire across the narrowing, and a balloon inflated to reopen the channel — sometimes followed by a stent. It is done awake, under local anaesthesia." },
    { q: "How long does a stent last?", a: "Many remain open for years. Durability depends on the vessel treated, lesion length, diabetes, kidney function and above all whether smoking stops." },
    { q: "What happens if the stent narrows again?", a: "Re-narrowing is usually treatable with a further balloon, often a drug-coated one. Surveillance is what allows it to be caught early." },
    { q: "Do I need surgery instead?", a: "Bypass is considered for very long blockages or when endovascular treatment fails. Most patients today are treated endovascularly first." },
    { q: "Why do I need a statin if my cholesterol is normal?", a: "Statins stabilise plaque and reduce heart attack and stroke risk in PAD independent of the starting cholesterol level." },
    { q: "Is PAD linked to heart disease?", a: "Strongly. The same process affects coronary and neck arteries, so cardiac and carotid assessment is part of good PAD care." },
    { q: "Can PAD cause erectile dysfunction?", a: "Yes, when the disease involves the aorto-iliac arteries. It can be the first symptom in some men." },
    { q: "What is critical limb ischemia?", a: "The advanced stage: pain at rest, ulceration or gangrene. It threatens the limb and requires prompt revascularisation." },
    { q: "How urgent is a suddenly cold, painful leg?", a: "An emergency. Acute limb ischemia has a window of a few hours before muscle and nerve damage becomes irreversible." },
    { q: "Does diabetes change the pattern of disease?", a: "Yes. Diabetic PAD tends to affect the smaller vessels below the knee, which requires different techniques and finer equipment." },
    { q: "Is contrast dye safe for my kidneys?", a: "Risk is managed with hydration, minimal contrast volume, and alternatives such as carbon dioxide angiography where kidney function is poor." },
    { q: "How often should I be followed up?", a: "Typically at one, three, six and twelve months after intervention, then yearly, with Doppler and pressure measurements each time." },
  ],
  relatedConditions: ["critical-limb-ischemia", "diabetic-foot", "aorto-iliac-disease", "carotid-artery-disease"],
  relatedSymptoms: ["Calf pain on walking", "Cold foot", "Rest pain at night", "Non-healing wound", "Hair loss on the legs"],
};
