import type { Pillar } from "./types";

export const poorCirculation: Pillar = {
  slug: "poor-blood-circulation",
  name: "Poor Blood Circulation",
  title: "Poor blood circulation",
  patientTerm: true,
  heroQuote: "My feet are always cold.",
  heroLead:
    "Poor circulation is not a diagnosis — it is a description. Behind it sits a specific, nameable problem: narrowed arteries, failing vein valves, a clot, or nerve damage from diabetes. Each has a different test and a different treatment. This page is written to help you find which one you have.",
  summary:
    "A patient term, not a disease. Cold feet, numbness, cramping or swelling usually point to arterial narrowing, vein valve failure, a clot or neuropathy — each with its own test and treatment.",

  symptoms: [
    "Cold hands or feet, especially on one side",
    "Numbness, tingling or a pins-and-needles feeling",
    "Cramping pain in the calves on walking",
    "Swelling of the ankles by evening",
    "Skin discoloration — pale, blue, brown or blackened",
    "Wounds that heal slowly or not at all",
    "Heaviness and aching in the legs",
    "Hair loss on the lower legs and shiny skin",
    "Night cramps or restless legs",
  ],
  causes: [
    "Peripheral arterial disease — narrowed arteries reducing flow into the limb",
    "Chronic venous insufficiency — failing vein valves so blood cannot leave the limb",
    "Deep vein thrombosis — a clot obstructing the outflow",
    "Diabetic neuropathy — nerve damage producing numbness and cold sensation with normal arteries",
    "Raynaud phenomenon — spasm of small arteries triggered by cold or stress",
    "Heart failure, causing swelling in both legs",
    "Anaemia and thyroid disease, producing generalised cold intolerance",
    "Smoking, which constricts vessels and accelerates arterial disease",
  ],
  riskFactors: [
    "Diabetes",
    "Smoking",
    "High blood pressure and high cholesterol",
    "Age above 50",
    "Obesity and physical inactivity",
    "Long hours standing or sitting",
    "Previous clot or leg injury",
    "Family history of vascular disease",
  ],
  warningSigns: [
    "Any wound on the foot that has not healed in two weeks",
    "Pain in the foot at rest or at night that eases when the leg hangs down",
    "Blackening of a toe",
    "Sudden swelling of one leg — this needs a clot scan the same day",
    "A suddenly cold, pale, painful, numb leg — an emergency",
  ],
  diagnosis: [
    { step: "History", detail: "The pattern is what separates the causes: pain on walking suggests arteries, evening swelling suggests veins, numbness with normal pulses suggests nerves, sudden one-sided swelling suggests a clot." },
    { step: "Clinical examination", detail: "Pulses at four levels in each leg, skin temperature and colour, ankle skin changes, and sensation testing with a monofilament." },
    { step: "Blood tests", detail: "Blood sugar and HbA1c, lipid profile, haemoglobin, thyroid function and kidney function." },
    { step: "Imaging", detail: "Arterial Doppler with ankle-brachial index for arteries, venous duplex for veins and clot. These two scans answer the question in most patients." },
  ],
  tests: [
    { name: "Ankle-brachial index", why: "A five-minute test comparing ankle and arm pressures. It confirms or excludes arterial narrowing before any expensive imaging is considered." },
    { name: "Arterial Doppler ultrasound", why: "Shows where flow is reduced and at what level, without contrast or radiation." },
    { name: "Venous duplex ultrasound", why: "Separates the two commonest causes — it detects both a clot and failing vein valves in the same examination." },
    { name: "Monofilament and vibration testing", why: "Identifies diabetic neuropathy, where the feet feel cold and numb although the circulation is normal. Treating this as an artery problem wastes months." },
    { name: "Blood sugar, thyroid and haemoglobin", why: "Diabetes, hypothyroidism and anaemia all produce a feeling of poor circulation and all are simple to treat." },
    { name: "CT angiography", why: "Reserved for when Doppler confirms significant arterial disease and treatment is being planned." },
  ],
  treatments: [
    { name: "Getting the right diagnosis", kind: "Observation", detail: "The most valuable step. Two ultrasound scans and a pressure index usually name the underlying condition precisely." },
    { name: "Angioplasty for arterial narrowing", kind: "Endovascular", detail: "Reopening the narrowed artery through a puncture, when Doppler and angiography confirm arterial disease." },
    { name: "Vein ablation for valve failure", kind: "Ablation", detail: "Sealing the refluxing vein when duplex shows venous insufficiency as the cause of swelling and heaviness." },
    { name: "Anticoagulation for clot", kind: "Medication", detail: "Immediate treatment when duplex confirms deep vein thrombosis, with clot removal considered in extensive cases." },
    { name: "Diabetes and neuropathy care", kind: "Medication", detail: "Glycaemic control, foot protection and neuropathic pain medication where nerves rather than vessels are the problem." },
    { name: "Walking programme", kind: "Lifestyle", detail: "Regular walking improves both arterial collateral flow and venous return. It benefits nearly every cause on this list." },
    { name: "Smoking cessation", kind: "Lifestyle", detail: "The single most effective change for anyone with genuinely reduced arterial flow." },
  ],
  approach: [
    "The first job is to replace the phrase with a diagnosis. 'Poor circulation' cannot be treated; peripheral arterial disease, venous reflux, DVT and neuropathy each can.",
    "Both an arterial and a venous scan are arranged where the picture is unclear, since the two conditions frequently coexist and are routinely confused.",
    "Neuropathy is actively looked for, because numb, cold-feeling feet with normal pulses need foot protection rather than an angiogram.",
    "Only once the cause is named is a treatment offered — and it is the treatment for that specific condition.",
    "Risk factor control runs alongside whatever procedure is done, because it determines the long-term result.",
  ],
  procedures: ["angioplasty", "varicose-vein-ablation", "thrombectomy"],
  recovery: [
    { when: "Visit 1", what: "History, pulse and sensation examination, ankle-brachial index and blood tests — enough to point in the right direction the same day." },
    { when: "Within days", what: "Arterial and venous Doppler scans, which name the cause in the large majority of patients." },
    { when: "Week 1 to 2", what: "A written plan: medical treatment, a specific procedure, or reassurance that the vessels are normal and the cause is elsewhere." },
    { when: "Month 1 to 3", what: "Treatment carried out and reviewed. Walking distance, swelling or wound healing are used as the measure." },
    { when: "Month 6 and beyond", what: "Surveillance for whichever condition was diagnosed, and continued risk factor control." },
  ],
  prevention: [
    "Walk for thirty minutes most days",
    "Stop smoking",
    "Keep blood sugar, blood pressure and cholesterol at target",
    "Elevate the legs in the evening if they swell",
    "Move regularly on long journeys",
    "Inspect the feet daily if you have diabetes",
    "Have any non-healing wound or one-sided swelling assessed early rather than waiting",
  ],
  faqs: [
    { q: "Is poor circulation a real diagnosis?", a: "It is a patient description rather than a medical diagnosis. Behind it there is almost always a specific condition — arterial, venous, clot-related or neurological." },
    { q: "How do I know if my problem is arteries or veins?", a: "Arterial disease typically causes cramping on walking, cold feet and non-healing wounds. Venous disease typically causes evening swelling, heaviness and ankle skin changes. A Doppler scan settles it." },
    { q: "Why are my feet always cold?", a: "Common causes are arterial narrowing, diabetic neuropathy, hypothyroidism, anaemia and Raynaud phenomenon. Each has a straightforward test." },
    { q: "Are cold feet always a circulation problem?", a: "No. Many people with cold feet have entirely normal arteries — nerve function and thyroid status are frequently the explanation." },
    { q: "What test should I ask for first?", a: "An ankle-brachial index and an arterial Doppler, plus a venous duplex if there is swelling. These three answer most cases." },
    { q: "Is numbness dangerous?", a: "Numbness itself, from neuropathy, means injuries go unnoticed. That is what makes it dangerous, particularly in diabetes." },
    { q: "Why do my legs swell only in the evening?", a: "That pattern is typical of venous insufficiency, where the leg fills through the day under gravity and empties overnight." },
    { q: "When is swelling an emergency?", a: "Sudden swelling of one leg over hours to days may be a deep vein thrombosis and needs an ultrasound the same day." },
    { q: "Does poor circulation cause hair loss on the legs?", a: "Reduced arterial flow does cause hair loss, shiny skin and slow nail growth on the lower legs." },
    { q: "Can circulation be improved by walking?", a: "Yes. Regular walking builds collateral arteries and drives the calf muscle pump that empties the veins." },
    { q: "Do circulation supplements work?", a: "There is little evidence for most over-the-counter supplements. Smoking cessation, walking and treating the specific underlying condition are what change outcomes." },
    { q: "Does massage help circulation?", a: "It can feel pleasant and helps lymphatic swelling, but it should never be done on a leg with a suspected clot." },
    { q: "Are compression stockings good for everyone?", a: "No. They help venous disease but can be harmful in significant arterial disease, which is why an ankle-brachial index is checked first." },
    { q: "Can diabetes cause poor circulation?", a: "Yes, through both arterial narrowing and nerve damage — and often both at once, which is why the feet need annual review." },
    { q: "Is smoking really that important?", a: "It is the most powerful modifiable factor for arterial disease in the limbs, and continuing to smoke undermines any procedure performed." },
    { q: "What is Raynaud phenomenon?", a: "Spasm of small arteries in the fingers or toes triggered by cold or stress, causing them to turn white, then blue, then red. It is usually benign but is investigated if severe." },
    { q: "Can heart problems cause leg symptoms?", a: "Yes. Heart failure typically causes swelling in both legs, which is a different pattern from one-sided clot or arterial disease." },
    { q: "Why do my legs cramp at night?", a: "Common causes include venous insufficiency, electrolyte imbalance, medication and, less often, arterial disease. The pattern and a scan distinguish them." },
    { q: "How long does it take to get an answer?", a: "In most cases a consultation and two ultrasound scans within a week are enough to give a specific diagnosis and a plan." },
    { q: "Which conditions should I read about next?", a: "Start with peripheral arterial disease if you have cramping on walking, varicose veins if you have evening swelling and heaviness, DVT if one leg swelled suddenly, and diabetic foot if you have a wound." },
  ],
  relatedConditions: ["peripheral-artery-disease", "varicose-veins", "deep-vein-thrombosis", "diabetic-foot"],
  relatedSymptoms: ["Cold feet", "Numbness and tingling", "Leg cramps on walking", "Ankle swelling", "Slow healing wounds"],
};
