import type { Pillar } from "./types";

export const thyroidNodules: Pillar = {
  slug: "thyroid-nodules",
  name: "Thyroid Nodules",
  title: "Thyroid nodules and swelling",
  heroQuote: "There's a lump in my neck.",
  heroLead:
    "Most thyroid nodules are benign, and most do not need surgery. A benign nodule that presses, shows or worries can be shrunk with a needle and heat, in an hour, leaving the thyroid gland and the neck intact.",
  summary:
    "Benign thyroid nodules can be treated without surgery. Radiofrequency or microwave ablation shrinks the nodule through a needle, preserving thyroid function and avoiding a neck scar.",

  symptoms: [
    "A visible or palpable lump in the front of the neck",
    "A sensation of pressure or tightness in the throat",
    "Difficulty swallowing solid food",
    "Change in voice or hoarseness",
    "Cough or a feeling of something stuck in the throat",
    "Breathlessness when lying flat, in large nodules",
    "Symptoms of an overactive gland — palpitations, weight loss, tremor, heat intolerance",
    "Symptoms of an underactive gland — fatigue, weight gain, cold intolerance",
  ],
  causes: [
    "Colloid nodules — the commonest, entirely benign overgrowth of normal tissue",
    "Thyroid cysts, sometimes filling rapidly and causing sudden swelling",
    "Follicular adenoma, a benign tumour",
    "Autonomously functioning ('hot') nodule producing excess hormone",
    "Hashimoto's thyroiditis producing a nodular gland",
    "Iodine deficiency causing multinodular goitre",
    "Thyroid cancer, in a small minority of nodules",
  ],
  riskFactors: [
    "Female sex",
    "Increasing age",
    "Iodine deficiency",
    "Family history of thyroid disease",
    "Previous radiation exposure to the head or neck",
    "Autoimmune thyroid disease",
    "Pregnancy, which can enlarge existing nodules",
  ],
  warningSigns: [
    "A nodule that is growing rapidly over weeks",
    "New, persistent hoarseness",
    "A hard, fixed lump that does not move on swallowing",
    "Enlarged lymph nodes in the neck",
    "Difficulty breathing or swallowing",
    "Any nodule appearing after childhood radiation exposure",
  ],
  diagnosis: [
    { step: "History", detail: "Duration and growth of the lump, pressure symptoms, voice change, radiation exposure and family history of thyroid cancer." },
    { step: "Clinical examination", detail: "Size, consistency and mobility of the nodule, whether it moves on swallowing, and whether neck nodes are enlarged." },
    { step: "Blood tests", detail: "TSH first, with free T4 and T3 where abnormal; thyroid antibodies where autoimmune disease is suspected; calcitonin in selected cases." },
    { step: "Imaging", detail: "High-resolution ultrasound with a standardised risk score, followed by fine-needle aspiration of nodules that meet criteria." },
  ],
  tests: [
    { name: "Thyroid ultrasound", why: "The decisive test. It measures the nodule and grades features — margins, echogenicity, microcalcification, shape — into a risk category that dictates whether a biopsy is needed." },
    { name: "TSH", why: "Separates a functioning nodule from a non-functioning one. A suppressed TSH points to a hot nodule, which is managed differently and rarely biopsied." },
    { name: "Fine-needle aspiration cytology", why: "A thin needle sample under ultrasound guidance. It is the only way to distinguish benign from malignant, and it is what makes non-surgical treatment safe to offer." },
    { name: "Radionuclide thyroid scan", why: "Used when TSH is low, to show whether the nodule is the source of excess hormone production." },
    { name: "CT of the neck and chest", why: "Reserved for very large goitres extending behind the breastbone, or where the airway is compressed." },
    { name: "Vocal cord check", why: "Assesses nerve function before any intervention, so that any change afterwards can be interpreted correctly." },
  ],
  treatments: [
    { name: "Observation with surveillance", kind: "Observation", detail: "Appropriate for small benign nodules without symptoms — repeat ultrasound rather than intervention." },
    { name: "Radiofrequency ablation", kind: "Ablation", detail: "A fine needle electrode is placed into the benign nodule under ultrasound and heat destroys it from within. It shrinks progressively over months while the rest of the gland is untouched." },
    { name: "Microwave ablation", kind: "Ablation", detail: "The same principle with microwave energy, often faster for larger nodules." },
    { name: "Ethanol ablation", kind: "Ablation", detail: "Preferred for pure cysts. Fluid is aspirated and alcohol instilled to prevent refilling." },
    { name: "Thyroid artery embolization", kind: "Endovascular", detail: "Blocking the arteries feeding a very large goitre to reduce its size and vascularity, used in selected cases including as a preparation for other treatment." },
    { name: "Anti-thyroid medication", kind: "Medication", detail: "Controls hormone excess in a functioning nodule while definitive treatment is planned." },
    { name: "Surgery", kind: "Surgery", detail: "Remains the treatment for malignant, suspicious or very large obstructive nodules, and involves removing part or all of the gland." },
  ],
  approach: [
    "Nothing is ablated until cytology confirms the nodule is benign, usually on two separate samples for solid nodules.",
    "Ultrasound is performed personally at the time of the procedure — the nodule and the danger zones are mapped before the needle is placed.",
    "Treatment is under local anaesthesia, with a hydrodissection barrier of fluid protecting the recurrent laryngeal nerve and oesophagus.",
    "The moving-shot technique treats the nodule in overlapping segments so no viable rim is left behind.",
    "Normal thyroid tissue is deliberately spared, so hormone replacement is usually not required afterwards.",
    "Patients go home the same day with no incision, and are followed with ultrasound at three, six and twelve months.",
  ],
  procedures: ["thyroid-ablation"],
  recovery: [
    { when: "Same day", what: "Two hours of observation, then discharge. Mild neck ache and a sensation of fullness are usual." },
    { when: "Days 1 to 3", what: "Simple analgesia if needed. Normal eating and speaking. Return to work usually the next day." },
    { when: "Week 1", what: "Any swelling settles. The nodule may briefly feel firmer before it starts to shrink." },
    { when: "Month 1 to 3", what: "Noticeable size reduction. Pressure symptoms typically improve first." },
    { when: "Month 6", what: "Ultrasound review; volume reduction of roughly half to four-fifths is typical for benign solid nodules." },
    { when: "Month 12", what: "Final assessment of shrinkage and thyroid function. A second session is occasionally offered for very large nodules." },
  ],
  prevention: [
    "Ensure adequate dietary iodine, primarily through iodised salt",
    "Have any new neck lump examined rather than watched at home",
    "Attend recommended ultrasound surveillance for known nodules",
    "Report voice change or swallowing difficulty promptly",
    "Avoid unnecessary radiation exposure to the neck",
    "Have thyroid function checked if there is a strong family history",
  ],
  faqs: [
    { q: "Are thyroid nodules cancerous?", a: "The large majority are benign. Ultrasound features and a needle biopsy determine which few require further attention." },
    { q: "Do all nodules need a biopsy?", a: "No. Biopsy is guided by size and ultrasound risk features. Small, clearly low-risk nodules are usually observed." },
    { q: "Can a nodule be treated without surgery?", a: "Yes. Benign nodules can be shrunk with radiofrequency or microwave ablation through a needle, with no incision and no removal of the gland." },
    { q: "Will I need thyroid hormone tablets afterwards?", a: "Usually not, because ablation targets the nodule and preserves surrounding normal thyroid tissue." },
    { q: "How much will the nodule shrink?", a: "Typically fifty to eighty percent of its volume over six to twelve months, with pressure symptoms improving earlier." },
    { q: "Is the procedure painful?", a: "It is done under local anaesthesia. Patients feel warmth and pressure, and occasionally an ache spreading to the jaw or ear that settles quickly." },
    { q: "How long does ablation take?", a: "Usually thirty to sixty minutes depending on nodule size." },
    { q: "Is there a scar?", a: "No. The needle leaves a puncture, unlike surgery which leaves a horizontal neck scar." },
    { q: "What are the risks?", a: "Voice change from nerve irritation, bleeding, skin burn and infection — all uncommon, and reduced by hydrodissection and ultrasound guidance." },
    { q: "Can ablation treat thyroid cancer?", a: "It is not the standard treatment for cancer. It may be considered for selected recurrent nodes or in patients unfit for surgery, always in a multidisciplinary setting." },
    { q: "What is a hot nodule?", a: "A nodule producing thyroid hormone independently, causing an overactive thyroid. It is identified by a low TSH and confirmed on a nuclear scan." },
    { q: "Can nodules come back after ablation?", a: "Regrowth can occur in a minority, more often in very large nodules. A repeat session is straightforward." },
    { q: "What is thyroid artery embolization?", a: "Blocking the small arteries supplying the gland through a catheter, used to reduce the size and blood supply of very large goitres in selected patients." },
    { q: "Why is my nodule causing hoarseness?", a: "Pressure on or involvement of the nerve to the voice box. New hoarseness requires prompt assessment as it can indicate a suspicious nodule." },
    { q: "Should I stop iodine supplements?", a: "Discuss with your physician. Both deficiency and excess can affect thyroid function, and it depends on your test results." },
    { q: "Does a multinodular goitre need treating?", a: "Only if it causes pressure symptoms, cosmetic concern, hormone excess, or if a nodule within it is suspicious." },
    { q: "Can nodules affect pregnancy?", a: "Nodules themselves usually do not, but thyroid hormone levels must be well controlled during pregnancy and are monitored closely." },
    { q: "How often should nodules be scanned?", a: "Commonly at six to twelve months initially, then less frequently if stable — the interval depends on the ultrasound risk category." },
    { q: "Is ablation available for cysts?", a: "Yes. Cysts respond very well to aspiration with ethanol instillation, often in a single session." },
    { q: "Will ablation affect my thyroid blood tests?", a: "Function generally remains unchanged for benign non-functioning nodules. Tests are repeated as part of follow-up." },
  ],
  relatedConditions: ["carotid-artery-disease"],
  relatedSymptoms: ["Neck lump", "Difficulty swallowing", "Hoarse voice", "Throat pressure", "Neck swelling"],
};
