import type { Pillar } from "./types";

export const uterineFibroids: Pillar = {
  slug: "uterine-fibroids",
  name: "Uterine Fibroids",
  title: "Uterine fibroids",
  heroQuote: "I've been told I need a hysterectomy.",
  heroLead:
    "Fibroids depend entirely on the blood supply reaching them. Blocking that supply through a catheter starves them while the uterus, fed by its own network, survives intact. Heavy bleeding settles, the fibroids shrink, and the uterus stays.",
  summary:
    "Heavy periods, pressure and pain from fibroids. Uterine fibroid embolization shrinks them through a pinhole in the wrist or groin, without removing the uterus.",

  symptoms: [
    "Heavy or prolonged menstrual bleeding, with clots",
    "Anaemia — fatigue, breathlessness, palpitations",
    "Pelvic pressure or a feeling of fullness",
    "Abdominal swelling that looks like weight gain",
    "Frequent urination from pressure on the bladder",
    "Constipation or difficulty passing stool",
    "Pain during intercourse",
    "Backache or leg pressure",
    "Difficulty conceiving, in some fibroid positions",
  ],
  causes: [
    "Benign overgrowth of the smooth muscle of the uterus",
    "Oestrogen and progesterone dependence, so fibroids grow during reproductive years",
    "Genetic changes within a single muscle cell that then multiplies",
    "Family predisposition",
  ],
  riskFactors: [
    "Age between 30 and 50",
    "Family history of fibroids",
    "Early onset of periods",
    "Obesity",
    "Never having been pregnant",
    "Vitamin D deficiency",
    "African ancestry, associated with earlier and larger fibroids",
  ],
  warningSigns: [
    "Soaking through protection hourly, or passing large clots — seek urgent care",
    "Dizziness, breathlessness or collapse from anaemia",
    "Sudden severe pelvic pain, which may indicate fibroid degeneration or torsion",
    "Rapid enlargement, especially after menopause, needs prompt assessment",
    "Inability to pass urine from pressure on the bladder neck",
  ],
  diagnosis: [
    { step: "History", detail: "Bleeding pattern and quantity, pressure symptoms, fertility plans, previous treatments and how far daily life is affected." },
    { step: "Clinical examination", detail: "Abdominal palpation for uterine size and pelvic examination to assess mobility, tenderness and position." },
    { step: "Blood tests", detail: "Haemoglobin and ferritin to quantify anaemia, thyroid function and clotting studies where bleeding is unusually heavy." },
    { step: "Imaging", detail: "Pelvic ultrasound first, then contrast MRI, which is the essential planning study before embolization." },
  ],
  tests: [
    { name: "Pelvic ultrasound", why: "The first-line test. It confirms fibroids, counts them and measures the uterus, and is quick and widely available." },
    { name: "Contrast-enhanced pelvic MRI", why: "The planning study for embolization. It maps every fibroid's size, position and blood supply, identifies adenomyosis, and flags fibroids unlikely to respond." },
    { name: "Haemoglobin and ferritin", why: "Quantifies the true cost of the bleeding. Severe anaemia may need correcting before any procedure." },
    { name: "Endometrial assessment", why: "Considered in irregular bleeding or in older women, to exclude a lining abnormality being blamed on fibroids." },
    { name: "Hysteroscopy", why: "Directly inspects the cavity when a submucosal fibroid or polyp is suspected as the bleeding source." },
    { name: "Pelvic angiography", why: "Performed at the time of treatment; it shows the uterine arteries and their variants, and confirms the fibroid blush being targeted." },
  ],
  treatments: [
    { name: "Observation", kind: "Observation", detail: "Appropriate for small, asymptomatic fibroids, particularly close to menopause when they naturally shrink." },
    { name: "Tranexamic acid and NSAIDs", kind: "Medication", detail: "Reduce menstrual blood loss during periods without affecting fibroid size." },
    { name: "Hormonal therapy", kind: "Medication", detail: "Progestogens, hormonal coils or GnRH analogues control bleeding and can temporarily shrink fibroids, with symptoms returning on stopping." },
    { name: "Iron replacement", kind: "Medication", detail: "Corrects anaemia — often the symptom patients feel most, and the fastest to improve." },
    { name: "Uterine fibroid embolization", kind: "Endovascular", detail: "Particles injected into both uterine arteries cut off fibroid blood supply. Bleeding improves within one to two cycles and fibroids shrink over months. The uterus is preserved." },
    { name: "Myomectomy", kind: "Surgery", detail: "Surgical removal of individual fibroids, preserving the uterus. Preferred in some fertility situations; fibroids can recur." },
    { name: "Hysterectomy", kind: "Surgery", detail: "Definitive, removing any possibility of recurrence, but ends fertility and requires major surgery and recovery." },
  ],
  approach: [
    "MRI before treatment is non-negotiable — it decides who will benefit and prevents treating a uterus whose real problem is adenomyosis alone.",
    "Access is usually radial, at the wrist, so patients can sit up and walk almost immediately.",
    "Both uterine arteries are embolized to the standard endpoint; treating one side alone leads to recurrence.",
    "Ovarian arterial supply is looked for specifically, as it is a known cause of treatment failure.",
    "Pain control is planned in advance, because the first twelve hours are the most uncomfortable part of the whole experience.",
    "Fertility intentions are discussed frankly and jointly with the gynaecologist before a route is chosen.",
  ],
  procedures: ["fibroid-embolization"],
  recovery: [
    { when: "Day 0", what: "Cramping pain, strongest in the first six to twelve hours, controlled with planned analgesia. Overnight stay is usual." },
    { when: "Days 1 to 3", what: "Discharge home. Cramping eases into an ache; mild fever and fatigue are expected as the fibroids infarct." },
    { when: "Week 1 to 2", what: "Return to office work in most cases. Mild vaginal discharge may occur." },
    { when: "Cycle 1 to 2", what: "Menstrual bleeding is usually noticeably lighter — often the first clear sign of success." },
    { when: "Month 3 to 6", what: "Fibroid volume falls substantially; pressure symptoms and abdominal swelling improve. MRI review at six months." },
    { when: "Year 1", what: "Symptom control is sustained in the large majority. Haemoglobin has normally recovered fully." },
  ],
  prevention: [
    "Maintain a healthy weight, as body fat influences oestrogen levels",
    "Correct vitamin D deficiency",
    "Treat heavy periods early rather than living with anaemia for years",
    "Attend gynaecological review if fibroids are known, to track growth",
    "Report any post-menopausal bleeding or rapid growth immediately",
    "Keep iron stores adequate during heavy-bleeding years",
  ],
  faqs: [
    { q: "What are uterine fibroids?", a: "Benign growths of the muscular wall of the uterus. They are extremely common and only need treatment when they cause symptoms." },
    { q: "Are fibroids cancerous?", a: "Almost never. Malignant change is rare, but rapid growth — especially after menopause — needs prompt assessment." },
    { q: "What is uterine fibroid embolization?", a: "Small particles are delivered through a catheter into both uterine arteries, blocking the fibroids' blood supply so they shrink, while the uterus survives on its remaining network." },
    { q: "Will I keep my uterus?", a: "Yes. That is the central purpose of the procedure." },
    { q: "How is it performed?", a: "Through a puncture at the wrist or groin under local anaesthesia and sedation, using X-ray guidance. It takes about an hour." },
    { q: "How painful is it?", a: "The procedure itself is not painful, but the following six to twelve hours bring strong period-like cramping, which is managed with planned pain relief and usually an overnight stay." },
    { q: "When will my bleeding improve?", a: "Usually within the first one or two menstrual cycles." },
    { q: "How much do fibroids shrink?", a: "Typically forty to sixty percent of volume by six months, with the uterus itself also reducing in size." },
    { q: "Can I get pregnant afterwards?", a: "Pregnancies after embolization are well documented, but where fertility is the primary goal, myomectomy is often preferred. This should be decided jointly with your gynaecologist." },
    { q: "Will it cause menopause?", a: "The risk of ovarian failure is low and rises with age, being more relevant in women over 45. It is discussed before treatment." },
    { q: "How long is the recovery?", a: "Most women return to office work within one to two weeks, considerably faster than after hysterectomy." },
    { q: "Can fibroids come back?", a: "Treated fibroids do not regrow, but new ones can develop over years. The recurrence rate is comparable to or lower than after myomectomy." },
    { q: "Is embolization better than hysterectomy?", a: "It is less invasive with faster recovery and preserves the uterus. Hysterectomy is definitive. The right choice depends on symptoms, age and priorities." },
    { q: "Does it treat adenomyosis?", a: "Embolization can improve adenomyosis symptoms, though results are less durable than for fibroids. MRI identifies whether it is present." },
    { q: "What are the risks?", a: "Post-embolization pain and fever, infection, fibroid tissue passing vaginally, non-target embolization and, uncommonly, ovarian impact." },
    { q: "Why is MRI needed before treatment?", a: "It shows which fibroids are present, their blood supply, and whether adenomyosis or another cause explains the symptoms. Ultrasound alone is not sufficient for planning." },
    { q: "Will I need a blood transfusion?", a: "Embolization involves negligible blood loss. Transfusion relates only to pre-existing severe anaemia." },
    { q: "Can very large fibroids be treated?", a: "Yes, though shrinkage takes longer and expectations are set accordingly. MRI guides suitability." },
    { q: "Is there a scar?", a: "No. There is a puncture at the wrist or groin, covered by a small dressing." },
    { q: "What if the procedure does not work?", a: "A minority of women need further treatment, either a repeat procedure or surgery. Embolization does not prevent surgery later." },
  ],
  relatedConditions: ["uterine-fibroids", "endometriosis-pelvic-congestion", "enlarged-prostate"],
  relatedSymptoms: ["Heavy periods", "Pelvic pressure", "Abdominal swelling", "Frequent urination", "Anaemia and fatigue"],
};
