import type { Pillar } from "./types";

export const varicoseVeins: Pillar = {
  slug: "varicose-veins",
  name: "Varicose Veins",
  title: "Varicose veins",
  heroQuote: "My legs ache by evening.",
  heroLead:
    "Valves inside the leg veins are meant to hold blood on its way up. When they fail, blood falls back and pools, and the vein widens into the ropes visible under the skin. The failing vein can be sealed from the inside — no stripping, no long scar.",
  summary:
    "Visible, aching, heavy legs caused by failing vein valves. Endovenous laser or radiofrequency ablation seals the refluxing vein through a needle puncture.",

  symptoms: [
    "Visible bulging, rope-like veins on the leg",
    "Aching or heaviness that worsens through the day",
    "Swelling around the ankle by evening",
    "Night cramps in the calf",
    "Itching or burning over a vein",
    "Restless legs at night",
    "Brown discoloration of the skin above the ankle",
    "Hardened, tight skin over the inner ankle",
    "An ulcer near the ankle that keeps returning",
  ],
  causes: [
    "Failure of the one-way valves in the great or small saphenous vein",
    "Reflux at the sapheno-femoral or sapheno-popliteal junction",
    "Perforator vein incompetence, allowing flow from deep to superficial veins",
    "Previous deep vein thrombosis damaging deep valves",
    "Pelvic vein reflux causing veins to appear high on the thigh or in the vulva",
    "Prolonged standing raising venous pressure over years",
  ],
  riskFactors: [
    "Family history of varicose veins",
    "Occupations requiring long hours standing — teaching, surgery, retail, security",
    "Pregnancy, and repeated pregnancies",
    "Obesity",
    "Increasing age",
    "Female sex, though men are frequently affected and often present later",
    "Previous DVT or leg injury",
  ],
  warningSigns: [
    "Skin darkening or hardening above the ankle — the vein disease has begun to damage the skin",
    "An ulcer at the inner ankle, or one that heals and returns",
    "Bleeding from a vein under the skin — lie down, elevate the leg and press",
    "A hot, hard, tender cord along the vein with fever, suggesting thrombophlebitis",
    "Sudden painful swelling of the whole calf, which must be assessed for DVT",
  ],
  diagnosis: [
    { step: "History", detail: "Duration, evening heaviness, cramps, previous clots or pregnancies, and how the legs affect work and sleep." },
    { step: "Clinical examination", detail: "The leg is examined standing, mapping visible veins, ankle skin changes, oedema and any ulcer." },
    { step: "Blood tests", detail: "Rarely required for diagnosis, but sugar, clotting and inflammatory markers are checked before intervention or when an ulcer is present." },
    { step: "Imaging", detail: "Duplex ultrasound performed standing is the entire diagnosis: it shows which vein refluxes, for how long, and where the leak starts." },
  ],
  tests: [
    { name: "Venous duplex ultrasound", why: "Combines picture and flow. Done standing, it measures reflux time in each vein and identifies the exact junction that has failed — the map on which treatment is planned." },
    { name: "Deep vein assessment", why: "Included in the same scan. The superficial vein must never be closed if the deep system is obstructed and carrying the load." },
    { name: "Pelvic vein imaging", why: "Reserved for veins appearing high on the thigh, buttock or vulva, or symptoms worse with periods — the source may be inside the pelvis." },
    { name: "Ankle-brachial index", why: "Checked before compression therapy. Firm compression on a leg with arterial disease can cause harm." },
  ],
  treatments: [
    { name: "Endovenous laser ablation", kind: "Ablation", detail: "A fibre is placed inside the failing vein through a needle puncture and energy seals it along its length. Walking the same day." },
    { name: "Radiofrequency ablation", kind: "Ablation", detail: "The same principle with controlled heat segments, often chosen for larger diameter veins." },
    { name: "Foam sclerotherapy", kind: "Endovascular", detail: "A foamed agent injected into tributaries and residual veins under ultrasound guidance, closing what ablation cannot reach." },
    { name: "Glue closure", kind: "Endovascular", detail: "A medical adhesive seals the vein without heat, avoiding tumescent anaesthesia in selected patients." },
    { name: "Ambulatory phlebectomy", kind: "Surgery", detail: "Bulging surface tributaries removed through pinhole incisions that require no stitches." },
    { name: "Compression stockings", kind: "Lifestyle", detail: "Graduated compression reduces symptoms and swelling. It controls the disease but does not correct the failed valve." },
    { name: "Observation", kind: "Observation", detail: "Reasonable for mild cosmetic veins with no reflux and no skin change, reviewed if symptoms progress." },
  ],
  approach: [
    "Nothing is treated until a standing duplex has shown which vein actually refluxes — visible veins are often not the source.",
    "The deep system is confirmed patent before any superficial vein is closed.",
    "Ablation is performed under local tumescent anaesthesia through a single needle puncture; general anaesthesia is not required.",
    "Tributaries are dealt with in the same sitting where appropriate, so that one visit closes the whole circuit.",
    "Patients walk immediately after and return to routine work within a day or two.",
    "Where an ulcer is present, closing the reflux is treated as the healing strategy, not an afterthought to dressings.",
  ],
  procedures: ["varicose-vein-ablation"],
  recovery: [
    { when: "Procedure: Day 0", what: "Discharged and walking within an hour of the procedure. Stockings applied." },
    { when: "Day 1", what: "Back to work / routine activity. Most people return to desk work immediately." },
    { when: "1 Week", what: "Normal lifestyle resume. Duplex check confirms the vein is closed." },
    { when: "1 Month", what: "Follow-up imaging and normal life. Discoloration fades and ulcers usually close." },
  ],

  prevention: [
    "Avoid standing still for long stretches — shift weight, walk a few steps each half hour",
    "Elevate the legs above hip level for fifteen minutes twice a day",
    "Wear graduated compression stockings if your work requires long standing",
    "Walk daily; calf muscle contraction is the pump the veins depend on",
    "Maintain a healthy weight",
    "Moisturise the skin above the ankle to prevent breakdown",
    "Have any recurring ankle ulcer scanned rather than repeatedly dressed",
  ],
  faqs: [
    { q: "What causes varicose veins?", a: "Failure of the one-way valves inside the leg veins, allowing blood to fall back and pool. The vein then widens under the extra pressure." },
    { q: "Are varicose veins only a cosmetic problem?", a: "No. Untreated reflux can progress to swelling, skin discoloration, hardening and ulceration at the ankle." },
    { q: "Is surgery still needed?", a: "Rarely. Vein stripping has largely been replaced by endovenous ablation performed through a needle puncture under local anaesthesia." },
    { q: "What is endovenous laser ablation?", a: "A thin fibre is passed inside the faulty vein and laser energy seals it along its length. Blood immediately reroutes through healthy veins." },
    { q: "Does the leg need that vein?", a: "No. The refluxing vein is already carrying blood in the wrong direction. Closing it improves overall drainage." },
    { q: "Is the procedure painful?", a: "Local anaesthesia is used along the vein. Patients typically feel pressure and cold fluid rather than pain." },
    { q: "How long does it take?", a: "Around forty-five to sixty minutes for one leg, including ultrasound mapping and treatment of tributaries." },
    { q: "Will I be admitted overnight?", a: "It is normally a day-care procedure. Patients walk out and go home the same day." },
    { q: "When can I return to work?", a: "Desk work usually within one or two days; heavy physical work after about a week." },
    { q: "Will there be scars?", a: "No long incision. Ablation leaves a needle puncture, and phlebectomy leaves pinholes that fade." },
    { q: "Can varicose veins come back?", a: "The treated vein stays closed, but new tributaries can develop over years. These are usually manageable with sclerotherapy." },
    { q: "Do compression stockings cure varicose veins?", a: "They relieve symptoms and slow progression but cannot repair a failed valve. They are a control measure, not a cure." },
    { q: "Are varicose veins dangerous in pregnancy?", a: "They often worsen in pregnancy and improve afterwards. Treatment is generally deferred until after delivery unless there is a complication." },
    { q: "Can varicose veins cause a clot?", a: "Superficial thrombophlebitis can occur, and extensive reflux is associated with a higher risk of deep vein thrombosis. Sudden painful swelling should be scanned." },
    { q: "Why do my legs ache more in the evening?", a: "Venous pressure accumulates through the day while standing. Elevation and overnight rest empty the veins, which is why mornings feel better." },
    { q: "What causes the brown skin above my ankle?", a: "Iron pigment deposited from blood leaking out of high-pressure veins. Early treatment can partially reverse it; late change is permanent." },
    { q: "Can a venous ulcer heal without treating the veins?", a: "It may close with dressings and compression, but it recurs frequently unless the underlying reflux is corrected." },
    { q: "Is laser or radiofrequency better?", a: "Both close the vein reliably. The choice depends on vein diameter, tortuosity and how close the vein runs to skin or nerves." },
    { q: "Do I need a scan before treatment?", a: "Always. A standing duplex ultrasound decides which vein is treated. Treating visible veins without mapping leads to recurrence." },
    { q: "Will insurance consider this cosmetic?", a: "Symptomatic reflux with documented duplex findings, skin change or ulceration is a medical condition. Documentation from the scan is what supports this." },
  ],
  relatedConditions: ["venous-ulcer", "deep-vein-thrombosis", "endometriosis-pelvic-congestion"],
  relatedSymptoms: ["Aching heavy legs", "Ankle swelling", "Night cramps", "Skin discoloration above the ankle", "Recurring ankle ulcer"],
};
