/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}.index'
import { Route as Char123LocaleChar125TestimonialsRouteImport } from './routes/{-$locale}.testimonials'
import { Route as Char123LocaleChar125SecondOpinionRouteImport } from './routes/{-$locale}.second-opinion'
import { Route as Char123LocaleChar125ResourcesRouteImport } from './routes/{-$locale}.resources'
import { Route as Char123LocaleChar125MediaRouteImport } from './routes/{-$locale}.media'
import { Route as Char123LocaleChar125ExpertiseRouteImport } from './routes/{-$locale}.expertise'
import { Route as Char123LocaleChar125ContactRouteImport } from './routes/{-$locale}.contact'
import { Route as Char123LocaleChar125AboutRouteImport } from './routes/{-$locale}.about'
import { Route as Char123LocaleChar125ProceduresIndexRouteImport } from './routes/{-$locale}.procedures.index'
import { Route as Char123LocaleChar125DiseasesIndexRouteImport } from './routes/{-$locale}.diseases.index'
import { Route as Char123LocaleChar125ConditionsIndexRouteImport } from './routes/{-$locale}.conditions.index'
import { Route as Char123LocaleChar125ProceduresSlugRouteImport } from './routes/{-$locale}.procedures.$slug'
import { Route as Char123LocaleChar125PatientInformationPreparingForTreatmentRouteImport } from './routes/{-$locale}.patient-information.preparing-for-treatment'
import { Route as Char123LocaleChar125PatientInformationHowTreatmentWorksRouteImport } from './routes/{-$locale}.patient-information.how-treatment-works'
import { Route as Char123LocaleChar125PatientInformationBeforeConsultationRouteImport } from './routes/{-$locale}.patient-information.before-consultation'
import { Route as Char123LocaleChar125PatientInformationAfterTreatmentRouteImport } from './routes/{-$locale}.patient-information.after-treatment'
import { Route as Char123LocaleChar125DiseasesSlugRouteImport } from './routes/{-$locale}.diseases.$slug'
import { Route as Char123LocaleChar125ConditionsSlugRouteImport } from './routes/{-$locale}.conditions.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/{-$locale}/',
    path: '/{-$locale}/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125TestimonialsRoute =
  Char123LocaleChar125TestimonialsRouteImport.update({
    id: '/{-$locale}/testimonials',
    path: '/{-$locale}/testimonials',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125SecondOpinionRoute =
  Char123LocaleChar125SecondOpinionRouteImport.update({
    id: '/{-$locale}/second-opinion',
    path: '/{-$locale}/second-opinion',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125ResourcesRoute =
  Char123LocaleChar125ResourcesRouteImport.update({
    id: '/{-$locale}/resources',
    path: '/{-$locale}/resources',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125MediaRoute =
  Char123LocaleChar125MediaRouteImport.update({
    id: '/{-$locale}/media',
    path: '/{-$locale}/media',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125ExpertiseRoute =
  Char123LocaleChar125ExpertiseRouteImport.update({
    id: '/{-$locale}/expertise',
    path: '/{-$locale}/expertise',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125ContactRoute =
  Char123LocaleChar125ContactRouteImport.update({
    id: '/{-$locale}/contact',
    path: '/{-$locale}/contact',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125AboutRoute =
  Char123LocaleChar125AboutRouteImport.update({
    id: '/{-$locale}/about',
    path: '/{-$locale}/about',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125ProceduresIndexRoute =
  Char123LocaleChar125ProceduresIndexRouteImport.update({
    id: '/{-$locale}/procedures/',
    path: '/{-$locale}/procedures/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125DiseasesIndexRoute =
  Char123LocaleChar125DiseasesIndexRouteImport.update({
    id: '/{-$locale}/diseases/',
    path: '/{-$locale}/diseases/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125ConditionsIndexRoute =
  Char123LocaleChar125ConditionsIndexRouteImport.update({
    id: '/{-$locale}/conditions/',
    path: '/{-$locale}/conditions/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125ProceduresSlugRoute =
  Char123LocaleChar125ProceduresSlugRouteImport.update({
    id: '/{-$locale}/procedures/$slug',
    path: '/{-$locale}/procedures/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125PatientInformationPreparingForTreatmentRoute =
  Char123LocaleChar125PatientInformationPreparingForTreatmentRouteImport.update(
    {
      id: '/{-$locale}/patient-information/preparing-for-treatment',
      path: '/{-$locale}/patient-information/preparing-for-treatment',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const Char123LocaleChar125PatientInformationHowTreatmentWorksRoute =
  Char123LocaleChar125PatientInformationHowTreatmentWorksRouteImport.update({
    id: '/{-$locale}/patient-information/how-treatment-works',
    path: '/{-$locale}/patient-information/how-treatment-works',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125PatientInformationBeforeConsultationRoute =
  Char123LocaleChar125PatientInformationBeforeConsultationRouteImport.update({
    id: '/{-$locale}/patient-information/before-consultation',
    path: '/{-$locale}/patient-information/before-consultation',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125PatientInformationAfterTreatmentRoute =
  Char123LocaleChar125PatientInformationAfterTreatmentRouteImport.update({
    id: '/{-$locale}/patient-information/after-treatment',
    path: '/{-$locale}/patient-information/after-treatment',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125DiseasesSlugRoute =
  Char123LocaleChar125DiseasesSlugRouteImport.update({
    id: '/{-$locale}/diseases/$slug',
    path: '/{-$locale}/diseases/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125ConditionsSlugRoute =
  Char123LocaleChar125ConditionsSlugRouteImport.update({
    id: '/{-$locale}/conditions/$slug',
    path: '/{-$locale}/conditions/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/{-$locale}/expertise': typeof Char123LocaleChar125ExpertiseRoute
  '/{-$locale}/media': typeof Char123LocaleChar125MediaRoute
  '/{-$locale}/resources': typeof Char123LocaleChar125ResourcesRoute
  '/{-$locale}/second-opinion': typeof Char123LocaleChar125SecondOpinionRoute
  '/{-$locale}/testimonials': typeof Char123LocaleChar125TestimonialsRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/conditions/$slug': typeof Char123LocaleChar125ConditionsSlugRoute
  '/{-$locale}/diseases/$slug': typeof Char123LocaleChar125DiseasesSlugRoute
  '/{-$locale}/patient-information/after-treatment': typeof Char123LocaleChar125PatientInformationAfterTreatmentRoute
  '/{-$locale}/patient-information/before-consultation': typeof Char123LocaleChar125PatientInformationBeforeConsultationRoute
  '/{-$locale}/patient-information/how-treatment-works': typeof Char123LocaleChar125PatientInformationHowTreatmentWorksRoute
  '/{-$locale}/patient-information/preparing-for-treatment': typeof Char123LocaleChar125PatientInformationPreparingForTreatmentRoute
  '/{-$locale}/procedures/$slug': typeof Char123LocaleChar125ProceduresSlugRoute
  '/{-$locale}/conditions/': typeof Char123LocaleChar125ConditionsIndexRoute
  '/{-$locale}/diseases/': typeof Char123LocaleChar125DiseasesIndexRoute
  '/{-$locale}/procedures/': typeof Char123LocaleChar125ProceduresIndexRoute
}
export interface FileRoutesByTo {
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/{-$locale}/expertise': typeof Char123LocaleChar125ExpertiseRoute
  '/{-$locale}/media': typeof Char123LocaleChar125MediaRoute
  '/{-$locale}/resources': typeof Char123LocaleChar125ResourcesRoute
  '/{-$locale}/second-opinion': typeof Char123LocaleChar125SecondOpinionRoute
  '/{-$locale}/testimonials': typeof Char123LocaleChar125TestimonialsRoute
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/conditions/$slug': typeof Char123LocaleChar125ConditionsSlugRoute
  '/{-$locale}/diseases/$slug': typeof Char123LocaleChar125DiseasesSlugRoute
  '/{-$locale}/patient-information/after-treatment': typeof Char123LocaleChar125PatientInformationAfterTreatmentRoute
  '/{-$locale}/patient-information/before-consultation': typeof Char123LocaleChar125PatientInformationBeforeConsultationRoute
  '/{-$locale}/patient-information/how-treatment-works': typeof Char123LocaleChar125PatientInformationHowTreatmentWorksRoute
  '/{-$locale}/patient-information/preparing-for-treatment': typeof Char123LocaleChar125PatientInformationPreparingForTreatmentRoute
  '/{-$locale}/procedures/$slug': typeof Char123LocaleChar125ProceduresSlugRoute
  '/{-$locale}/conditions': typeof Char123LocaleChar125ConditionsIndexRoute
  '/{-$locale}/diseases': typeof Char123LocaleChar125DiseasesIndexRoute
  '/{-$locale}/procedures': typeof Char123LocaleChar125ProceduresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/{-$locale}/expertise': typeof Char123LocaleChar125ExpertiseRoute
  '/{-$locale}/media': typeof Char123LocaleChar125MediaRoute
  '/{-$locale}/resources': typeof Char123LocaleChar125ResourcesRoute
  '/{-$locale}/second-opinion': typeof Char123LocaleChar125SecondOpinionRoute
  '/{-$locale}/testimonials': typeof Char123LocaleChar125TestimonialsRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/conditions/$slug': typeof Char123LocaleChar125ConditionsSlugRoute
  '/{-$locale}/diseases/$slug': typeof Char123LocaleChar125DiseasesSlugRoute
  '/{-$locale}/patient-information/after-treatment': typeof Char123LocaleChar125PatientInformationAfterTreatmentRoute
  '/{-$locale}/patient-information/before-consultation': typeof Char123LocaleChar125PatientInformationBeforeConsultationRoute
  '/{-$locale}/patient-information/how-treatment-works': typeof Char123LocaleChar125PatientInformationHowTreatmentWorksRoute
  '/{-$locale}/patient-information/preparing-for-treatment': typeof Char123LocaleChar125PatientInformationPreparingForTreatmentRoute
  '/{-$locale}/procedures/$slug': typeof Char123LocaleChar125ProceduresSlugRoute
  '/{-$locale}/conditions/': typeof Char123LocaleChar125ConditionsIndexRoute
  '/{-$locale}/diseases/': typeof Char123LocaleChar125DiseasesIndexRoute
  '/{-$locale}/procedures/': typeof Char123LocaleChar125ProceduresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/sitemap.xml'
    | '/{-$locale}/about'
    | '/{-$locale}/contact'
    | '/{-$locale}/expertise'
    | '/{-$locale}/media'
    | '/{-$locale}/resources'
    | '/{-$locale}/second-opinion'
    | '/{-$locale}/testimonials'
    | '/{-$locale}/'
    | '/{-$locale}/conditions/$slug'
    | '/{-$locale}/diseases/$slug'
    | '/{-$locale}/patient-information/after-treatment'
    | '/{-$locale}/patient-information/before-consultation'
    | '/{-$locale}/patient-information/how-treatment-works'
    | '/{-$locale}/patient-information/preparing-for-treatment'
    | '/{-$locale}/procedures/$slug'
    | '/{-$locale}/conditions/'
    | '/{-$locale}/diseases/'
    | '/{-$locale}/procedures/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sitemap.xml'
    | '/{-$locale}/about'
    | '/{-$locale}/contact'
    | '/{-$locale}/expertise'
    | '/{-$locale}/media'
    | '/{-$locale}/resources'
    | '/{-$locale}/second-opinion'
    | '/{-$locale}/testimonials'
    | '/{-$locale}'
    | '/{-$locale}/conditions/$slug'
    | '/{-$locale}/diseases/$slug'
    | '/{-$locale}/patient-information/after-treatment'
    | '/{-$locale}/patient-information/before-consultation'
    | '/{-$locale}/patient-information/how-treatment-works'
    | '/{-$locale}/patient-information/preparing-for-treatment'
    | '/{-$locale}/procedures/$slug'
    | '/{-$locale}/conditions'
    | '/{-$locale}/diseases'
    | '/{-$locale}/procedures'
  id:
    | '__root__'
    | '/sitemap.xml'
    | '/{-$locale}/about'
    | '/{-$locale}/contact'
    | '/{-$locale}/expertise'
    | '/{-$locale}/media'
    | '/{-$locale}/resources'
    | '/{-$locale}/second-opinion'
    | '/{-$locale}/testimonials'
    | '/{-$locale}/'
    | '/{-$locale}/conditions/$slug'
    | '/{-$locale}/diseases/$slug'
    | '/{-$locale}/patient-information/after-treatment'
    | '/{-$locale}/patient-information/before-consultation'
    | '/{-$locale}/patient-information/how-treatment-works'
    | '/{-$locale}/patient-information/preparing-for-treatment'
    | '/{-$locale}/procedures/$slug'
    | '/{-$locale}/conditions/'
    | '/{-$locale}/diseases/'
    | '/{-$locale}/procedures/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char123LocaleChar125AboutRoute: typeof Char123LocaleChar125AboutRoute
  Char123LocaleChar125ContactRoute: typeof Char123LocaleChar125ContactRoute
  Char123LocaleChar125ExpertiseRoute: typeof Char123LocaleChar125ExpertiseRoute
  Char123LocaleChar125MediaRoute: typeof Char123LocaleChar125MediaRoute
  Char123LocaleChar125ResourcesRoute: typeof Char123LocaleChar125ResourcesRoute
  Char123LocaleChar125SecondOpinionRoute: typeof Char123LocaleChar125SecondOpinionRoute
  Char123LocaleChar125TestimonialsRoute: typeof Char123LocaleChar125TestimonialsRoute
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
  Char123LocaleChar125ConditionsSlugRoute: typeof Char123LocaleChar125ConditionsSlugRoute
  Char123LocaleChar125DiseasesSlugRoute: typeof Char123LocaleChar125DiseasesSlugRoute
  Char123LocaleChar125PatientInformationAfterTreatmentRoute: typeof Char123LocaleChar125PatientInformationAfterTreatmentRoute
  Char123LocaleChar125PatientInformationBeforeConsultationRoute: typeof Char123LocaleChar125PatientInformationBeforeConsultationRoute
  Char123LocaleChar125PatientInformationHowTreatmentWorksRoute: typeof Char123LocaleChar125PatientInformationHowTreatmentWorksRoute
  Char123LocaleChar125PatientInformationPreparingForTreatmentRoute: typeof Char123LocaleChar125PatientInformationPreparingForTreatmentRoute
  Char123LocaleChar125ProceduresSlugRoute: typeof Char123LocaleChar125ProceduresSlugRoute
  Char123LocaleChar125ConditionsIndexRoute: typeof Char123LocaleChar125ConditionsIndexRoute
  Char123LocaleChar125DiseasesIndexRoute: typeof Char123LocaleChar125DiseasesIndexRoute
  Char123LocaleChar125ProceduresIndexRoute: typeof Char123LocaleChar125ProceduresIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/{-$locale}'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/testimonials': {
      id: '/{-$locale}/testimonials'
      path: '/{-$locale}/testimonials'
      fullPath: '/{-$locale}/testimonials'
      preLoaderRoute: typeof Char123LocaleChar125TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/second-opinion': {
      id: '/{-$locale}/second-opinion'
      path: '/{-$locale}/second-opinion'
      fullPath: '/{-$locale}/second-opinion'
      preLoaderRoute: typeof Char123LocaleChar125SecondOpinionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/resources': {
      id: '/{-$locale}/resources'
      path: '/{-$locale}/resources'
      fullPath: '/{-$locale}/resources'
      preLoaderRoute: typeof Char123LocaleChar125ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/media': {
      id: '/{-$locale}/media'
      path: '/{-$locale}/media'
      fullPath: '/{-$locale}/media'
      preLoaderRoute: typeof Char123LocaleChar125MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/expertise': {
      id: '/{-$locale}/expertise'
      path: '/{-$locale}/expertise'
      fullPath: '/{-$locale}/expertise'
      preLoaderRoute: typeof Char123LocaleChar125ExpertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/contact': {
      id: '/{-$locale}/contact'
      path: '/{-$locale}/contact'
      fullPath: '/{-$locale}/contact'
      preLoaderRoute: typeof Char123LocaleChar125ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/about': {
      id: '/{-$locale}/about'
      path: '/{-$locale}/about'
      fullPath: '/{-$locale}/about'
      preLoaderRoute: typeof Char123LocaleChar125AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/procedures/': {
      id: '/{-$locale}/procedures/'
      path: '/{-$locale}/procedures'
      fullPath: '/{-$locale}/procedures/'
      preLoaderRoute: typeof Char123LocaleChar125ProceduresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/diseases/': {
      id: '/{-$locale}/diseases/'
      path: '/{-$locale}/diseases'
      fullPath: '/{-$locale}/diseases/'
      preLoaderRoute: typeof Char123LocaleChar125DiseasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/conditions/': {
      id: '/{-$locale}/conditions/'
      path: '/{-$locale}/conditions'
      fullPath: '/{-$locale}/conditions/'
      preLoaderRoute: typeof Char123LocaleChar125ConditionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/procedures/$slug': {
      id: '/{-$locale}/procedures/$slug'
      path: '/{-$locale}/procedures/$slug'
      fullPath: '/{-$locale}/procedures/$slug'
      preLoaderRoute: typeof Char123LocaleChar125ProceduresSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/patient-information/preparing-for-treatment': {
      id: '/{-$locale}/patient-information/preparing-for-treatment'
      path: '/{-$locale}/patient-information/preparing-for-treatment'
      fullPath: '/{-$locale}/patient-information/preparing-for-treatment'
      preLoaderRoute: typeof Char123LocaleChar125PatientInformationPreparingForTreatmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/patient-information/how-treatment-works': {
      id: '/{-$locale}/patient-information/how-treatment-works'
      path: '/{-$locale}/patient-information/how-treatment-works'
      fullPath: '/{-$locale}/patient-information/how-treatment-works'
      preLoaderRoute: typeof Char123LocaleChar125PatientInformationHowTreatmentWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/patient-information/before-consultation': {
      id: '/{-$locale}/patient-information/before-consultation'
      path: '/{-$locale}/patient-information/before-consultation'
      fullPath: '/{-$locale}/patient-information/before-consultation'
      preLoaderRoute: typeof Char123LocaleChar125PatientInformationBeforeConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/patient-information/after-treatment': {
      id: '/{-$locale}/patient-information/after-treatment'
      path: '/{-$locale}/patient-information/after-treatment'
      fullPath: '/{-$locale}/patient-information/after-treatment'
      preLoaderRoute: typeof Char123LocaleChar125PatientInformationAfterTreatmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/diseases/$slug': {
      id: '/{-$locale}/diseases/$slug'
      path: '/{-$locale}/diseases/$slug'
      fullPath: '/{-$locale}/diseases/$slug'
      preLoaderRoute: typeof Char123LocaleChar125DiseasesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/conditions/$slug': {
      id: '/{-$locale}/conditions/$slug'
      path: '/{-$locale}/conditions/$slug'
      fullPath: '/{-$locale}/conditions/$slug'
      preLoaderRoute: typeof Char123LocaleChar125ConditionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char123LocaleChar125AboutRoute: Char123LocaleChar125AboutRoute,
  Char123LocaleChar125ContactRoute: Char123LocaleChar125ContactRoute,
  Char123LocaleChar125ExpertiseRoute: Char123LocaleChar125ExpertiseRoute,
  Char123LocaleChar125MediaRoute: Char123LocaleChar125MediaRoute,
  Char123LocaleChar125ResourcesRoute: Char123LocaleChar125ResourcesRoute,
  Char123LocaleChar125SecondOpinionRoute:
    Char123LocaleChar125SecondOpinionRoute,
  Char123LocaleChar125TestimonialsRoute: Char123LocaleChar125TestimonialsRoute,
  Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
  Char123LocaleChar125ConditionsSlugRoute:
    Char123LocaleChar125ConditionsSlugRoute,
  Char123LocaleChar125DiseasesSlugRoute: Char123LocaleChar125DiseasesSlugRoute,
  Char123LocaleChar125PatientInformationAfterTreatmentRoute:
    Char123LocaleChar125PatientInformationAfterTreatmentRoute,
  Char123LocaleChar125PatientInformationBeforeConsultationRoute:
    Char123LocaleChar125PatientInformationBeforeConsultationRoute,
  Char123LocaleChar125PatientInformationHowTreatmentWorksRoute:
    Char123LocaleChar125PatientInformationHowTreatmentWorksRoute,
  Char123LocaleChar125PatientInformationPreparingForTreatmentRoute:
    Char123LocaleChar125PatientInformationPreparingForTreatmentRoute,
  Char123LocaleChar125ProceduresSlugRoute:
    Char123LocaleChar125ProceduresSlugRoute,
  Char123LocaleChar125ConditionsIndexRoute:
    Char123LocaleChar125ConditionsIndexRoute,
  Char123LocaleChar125DiseasesIndexRoute:
    Char123LocaleChar125DiseasesIndexRoute,
  Char123LocaleChar125ProceduresIndexRoute:
    Char123LocaleChar125ProceduresIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
