/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ExpertiseRouteImport } from './routes/expertise'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProceduresIndexRouteImport } from './routes/procedures.index'
import { Route as DiseasesIndexRouteImport } from './routes/diseases.index'
import { Route as ConditionsIndexRouteImport } from './routes/conditions.index'
import { Route as ProceduresSlugRouteImport } from './routes/procedures.$slug'
import { Route as DiseasesSlugRouteImport } from './routes/diseases.$slug'
import { Route as ConditionsSlugRouteImport } from './routes/conditions.$slug'

const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertiseRoute = ExpertiseRouteImport.update({
  id: '/expertise',
  path: '/expertise',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProceduresIndexRoute = ProceduresIndexRouteImport.update({
  id: '/procedures/',
  path: '/procedures/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiseasesIndexRoute = DiseasesIndexRouteImport.update({
  id: '/diseases/',
  path: '/diseases/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsIndexRoute = ConditionsIndexRouteImport.update({
  id: '/conditions/',
  path: '/conditions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProceduresSlugRoute = ProceduresSlugRouteImport.update({
  id: '/procedures/$slug',
  path: '/procedures/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DiseasesSlugRoute = DiseasesSlugRouteImport.update({
  id: '/diseases/$slug',
  path: '/diseases/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsSlugRoute = ConditionsSlugRouteImport.update({
  id: '/conditions/$slug',
  path: '/conditions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/expertise': typeof ExpertiseRoute
  '/resources': typeof ResourcesRoute
  '/testimonials': typeof TestimonialsRoute
  '/conditions/$slug': typeof ConditionsSlugRoute
  '/diseases/$slug': typeof DiseasesSlugRoute
  '/procedures/$slug': typeof ProceduresSlugRoute
  '/conditions/': typeof ConditionsIndexRoute
  '/diseases/': typeof DiseasesIndexRoute
  '/procedures/': typeof ProceduresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/expertise': typeof ExpertiseRoute
  '/resources': typeof ResourcesRoute
  '/testimonials': typeof TestimonialsRoute
  '/conditions/$slug': typeof ConditionsSlugRoute
  '/diseases/$slug': typeof DiseasesSlugRoute
  '/procedures/$slug': typeof ProceduresSlugRoute
  '/conditions': typeof ConditionsIndexRoute
  '/diseases': typeof DiseasesIndexRoute
  '/procedures': typeof ProceduresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/expertise': typeof ExpertiseRoute
  '/resources': typeof ResourcesRoute
  '/testimonials': typeof TestimonialsRoute
  '/conditions/$slug': typeof ConditionsSlugRoute
  '/diseases/$slug': typeof DiseasesSlugRoute
  '/procedures/$slug': typeof ProceduresSlugRoute
  '/conditions/': typeof ConditionsIndexRoute
  '/diseases/': typeof DiseasesIndexRoute
  '/procedures/': typeof ProceduresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/expertise'
    | '/resources'
    | '/testimonials'
    | '/conditions/$slug'
    | '/diseases/$slug'
    | '/procedures/$slug'
    | '/conditions/'
    | '/diseases/'
    | '/procedures/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/expertise'
    | '/resources'
    | '/testimonials'
    | '/conditions/$slug'
    | '/diseases/$slug'
    | '/procedures/$slug'
    | '/conditions'
    | '/diseases'
    | '/procedures'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/expertise'
    | '/resources'
    | '/testimonials'
    | '/conditions/$slug'
    | '/diseases/$slug'
    | '/procedures/$slug'
    | '/conditions/'
    | '/diseases/'
    | '/procedures/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ExpertiseRoute: typeof ExpertiseRoute
  ResourcesRoute: typeof ResourcesRoute
  TestimonialsRoute: typeof TestimonialsRoute
  ConditionsSlugRoute: typeof ConditionsSlugRoute
  DiseasesSlugRoute: typeof DiseasesSlugRoute
  ProceduresSlugRoute: typeof ProceduresSlugRoute
  ConditionsIndexRoute: typeof ConditionsIndexRoute
  DiseasesIndexRoute: typeof DiseasesIndexRoute
  ProceduresIndexRoute: typeof ProceduresIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expertise': {
      id: '/expertise'
      path: '/expertise'
      fullPath: '/expertise'
      preLoaderRoute: typeof ExpertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procedures/': {
      id: '/procedures/'
      path: '/procedures'
      fullPath: '/procedures/'
      preLoaderRoute: typeof ProceduresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diseases/': {
      id: '/diseases/'
      path: '/diseases'
      fullPath: '/diseases/'
      preLoaderRoute: typeof DiseasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions/': {
      id: '/conditions/'
      path: '/conditions'
      fullPath: '/conditions/'
      preLoaderRoute: typeof ConditionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procedures/$slug': {
      id: '/procedures/$slug'
      path: '/procedures/$slug'
      fullPath: '/procedures/$slug'
      preLoaderRoute: typeof ProceduresSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diseases/$slug': {
      id: '/diseases/$slug'
      path: '/diseases/$slug'
      fullPath: '/diseases/$slug'
      preLoaderRoute: typeof DiseasesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions/$slug': {
      id: '/conditions/$slug'
      path: '/conditions/$slug'
      fullPath: '/conditions/$slug'
      preLoaderRoute: typeof ConditionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ExpertiseRoute: ExpertiseRoute,
  ResourcesRoute: ResourcesRoute,
  TestimonialsRoute: TestimonialsRoute,
  ConditionsSlugRoute: ConditionsSlugRoute,
  DiseasesSlugRoute: DiseasesSlugRoute,
  ProceduresSlugRoute: ProceduresSlugRoute,
  ConditionsIndexRoute: ConditionsIndexRoute,
  DiseasesIndexRoute: DiseasesIndexRoute,
  ProceduresIndexRoute: ProceduresIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
